import type { Product } from '@/types';
import { buildMetaDescription, htmlToText } from './sanitizeProductHtml';
import { formatTnd, getPriceDisplay } from './productPrice';
import { DELIVERY } from '@/util/company';

function normalize(text: string): string {
  return text.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase()
    .replace(/[^\p{L}\p{N}]+/gu, ' ').trim();
}

/** Imports vary punctuation and sometimes omit flavour/size tokens from the title. */
function withoutLeadingName(text: string, name: string, prose = false): string {
  const original = text;
  if (prose) text = text.replace(/^(?:(?:le|la|les|de|du)\s+|[ld][’'])/i, '');
  const nameWords = normalize(name).split(' ');
  const words = [...text.matchAll(/[\p{L}\p{N}]+/gu)];
  if (!words.length || normalize(words[0][0]) !== nameWords[0]) return original;
  let next = 0;
  let end = 0;
  let matched = 0;
  for (const word of words) {
    const normalized = normalize(word[0]);
    if (prose && matched > 0 && /^(?:de|d|du)$/.test(normalized)) continue;
    const at = nameWords.indexOf(normalized, next);
    if (at < 0) break;
    next = at + 1;
    end = word.index! + word[0].length;
    matched++;
  }
  if (matched < Math.min(prose ? 2 : 3, nameWords.length)) return original;
  return text.slice(end).replace(/^[\s\-–—:,.®™]+/u, '').trim();
}

/**
 * Classify the FULL explicit text, before its 160-character cut. Uniqueness is irrelevant:
 * remove identity and commerce-only clauses; any remaining words preserve the editor's copy.
 * Unlike a marker count, this keeps benefit copy even when followed by every delivery marker.
 * Identity values come from the product, so an arbitrary sentence after "marque" is not eaten.
 */
export function isFormulaicProductDescription(raw: string, product: Product, productName: string): boolean {
  let text = normalize(withoutLeadingName(htmlToText(raw, Infinity), productName));
  if (!normalize(raw)) return false;

  const identities = [
    product.brand?.designation_fr,
    product.sous_categorie?.designation_fr,
    product.sous_categorie?.categorie?.designation_fr,
    ...(product.sous_categories ?? []).flatMap((sub) => [sub.designation_fr, sub.categorie?.designation_fr]),
  ].filter((value): value is string => !!value).map(normalize).filter(Boolean);
  for (const identity of [...new Set(identities)].sort((a, b) => b.length - a.length)) {
    text = ` ${text} `.split(` ${identity} `).join(' ').trim();
  }
  const shopClauses = [
    /\bboutique de complements(?: alimentaires)? a sousse en tunisie\b/g,
    /\blivraison (?:24 72\s*h|rapide)(?: partout)?(?: en|dans toute la) tunisie\b/g,
    /\blivraison 24 72\s*h\b/g,
    /\bpaiement a la livraison\b/g,
    /\b(?:produits? )?(?:100 )?authentiques?\b/g,
    /\b(?:(?:sur|chez) )?(?:proteine tunisie|protein tn)\b/g,
    /\b(?:en vente |disponible )?en tunisie\b/g,
    /\bfiche produit du rayon\b/g,
    /\b(?:rayon|categorie|marque)\b/g,
    /\b\d+(?: \d+)? dt\b/g,
  ];
  for (const clause of shopClauses) text = text.replace(clause, ' ');
  return !text.trim();
}

/*
 * ── HUMAN PRODUCT NAMES, GLOBALLY ────────────────────────────────────────────────────────────
 * The catalogue stores product names the way a wholesaler types them: "100% CREATINE MONOHYDRATE
 * 300G - BIOTECH USA". Until 21/09/2026 that string was the <title> of almost every product page
 * (plus "– Prix Tunisie"), while the handful of pages an SEO pass had rewritten by hand
 * ("Serious Mass 5,45 kg – Prix Tunisie | Optimum Nutrition") were the ones that ranked. The
 * pattern of those hand rewrites is mechanical — sentence case, French units, brand moved to the
 * end — so it is applied here to every product instead of five. A title a human wrote in the CMS
 * still wins (see isAutoGeneratedTitle); only the auto-generated shouting ones are rewritten.
 */
const KEEP_UPPER = new Set([
  'USA', 'UK', 'EU', 'BCAA', 'BCAAS', 'EAA', 'EAAS', 'ZMA', 'HMB', 'CLA', 'MSM', 'ISO', 'XT', 'EFX',
  'HGH', 'ATP', 'GABA', 'CBD', 'MCT', 'XL', 'XXL', 'DHA', 'EPA', 'DAA', 'HCL', 'HCA', 'Q10', 'MK7',
  'ON', 'NO2', 'ZMB6', 'TNT', 'GH', 'L', 'D', 'C', 'E', 'K', 'B', 'A', 'MR.X', 'V8', 'C4', 'X',
  /*
   * Brand initialisms, taken from the shop's own brand table (24/09/2026) and limited to the
   * ones measured flattened inside SHOUTING catalogue names — 25 products. None is a word in
   * French or English, so uppercasing them cannot catch an unrelated token. The costliest was
   * GSN: /creatine/gsn-creatine-monohydrate-200g titled itself "Gsn – Creatine Monohydrate"
   * while sitting at position 7.0 on 272 impressions with 0 clicks (GSC 28 d to 22/09/2026).
   */
  'GSN', 'HX', 'MND', 'JX', 'BPI', 'IHS',
]);
/** French function words stay lowercase inside a title (never as the first word). */
const FRENCH_SMALL = new Set(['de', 'du', 'des', 'la', 'le', 'les', 'et', 'en', 'à', 'a', 'au', 'aux', 'pour', 'avec', 'sans', 'sur', 'par', 'ou', 'un', 'une']);

/** Unit and count words that follow a number: always lowercase ("2,27 kg", "60 caps"). */
const UNIT_WORDS = new Set(['kg', 'g', 'gr', 'mg', 'ml', 'l', 'caps', 'capsules', 'gelules', 'gélules', 'tabs', 'tablets', 'comprimes', 'comprimés', 'servings', 'softgel', 'softgels', 'doses', 'sachets']);

function caseToken(token: string, first: boolean): string {
  if (!token) return token;
  /*
   * Tokens are split on spaces, so they arrive with their punctuation still attached — "HMB,",
   * "(EAA)", "BCAA." — and every lookup below is on the bare word. Live on 23/09/2026:
   * "MuscleTech Clear Muscle, Liquid HMB, 84 Liquid Softgels" shipped its <title> as
   * "Liquid Hmb," because `KEEP_UPPER.has('HMB,')` is false. Peel the punctuation, case the
   * core, put the punctuation back. The recursion terminates: the core is strictly shorter.
   */
  const wrapped = token.match(/^([^\p{L}\p{N}]*)(.+?)([^\p{L}\p{N}]*)$/u);
  if (wrapped && (wrapped[1] || wrapped[3])) {
    return wrapped[1] + caseToken(wrapped[2], first) + wrapped[3];
  }
  const upper = token.toUpperCase();
  const lower = token.toLowerCase();
  if (KEEP_UPPER.has(upper)) return upper;
  if (UNIT_WORDS.has(lower)) return lower;
  /*
   * The micro sign "µ" (U+00B5) uppercases to GREEK CAPITAL MU "Μ", so the Titlecase branch at the
   * bottom turns a standalone "µg" into "Μg". The 24/09 pass fixed the GLUED form ("100µG" goes
   * down the digit branch below) but not the spaced one, and the 42-listing sample it was measured
   * over did not contain it. `title-case-check.mjs` over all 11,367 catalogue names on 25/09/2026
   * found "NATURELO Vitamin D3 – 62,5 µg" building as "… 62,5 Μg" — 2 products, both masked today
   * by a CMS seo_title, so this repairs the builder, not a live <title>. A token that starts with
   * the micro sign is a unit; it is never capitalised.
   */
  if (/^[\u00b5\u03bc]/.test(token)) return lower;
  if (/^[A-Z]\d+$/i.test(token)) return upper; // B6, D3, K2, C4
  if (/^[A-Z]{2,}\d+$/i.test(token)) return upper; // ISO100, NO2, C4
  if (/^\d/.test(token)) return lower.replace(/(\d)(kg|g|ml|l|mg)$/, (m, d, u) => d + u);
  if (token.includes('-')) return token.split('-').map((p, i) => caseToken(p, first && i === 0)).join('-');
  if (!first && FRENCH_SMALL.has(lower)) return lower;
  return lower.charAt(0).toUpperCase() + lower.slice(1);
}

/*
 * ── ONLY RE-CASE A NAME THAT IS ACTUALLY SHOUTING ────────────────────────────────────────────
 * The humanizer above exists for the wholesaler style ("100% CREATINE MONOHYDRATE 300G - BIOTECH
 * USA"). But it ran on EVERY name, and most of the catalogue is imported already correctly cased,
 * so it was destroying capitals rather than repairing them. Measured 24/09/2026 over 7,389 live
 * catalogue names: only 243 (3.3 %) are shouting, while 4,699 were being re-cased. Live examples:
 *
 *   "NOW Foods L-Theanine – 120 gélules végétales"  →  "Now Foods L-Theanine – 120 gélules Végétales"
 *   "EVLution Nutrition Resveratrol"                →  "Evlution Nutrition Resveratrol"
 *   "MuscleTech Clear Muscle"                       →  "Muscletech Clear Muscle"
 *
 * A brand rendered "Now Foods" or "Muscletech" in the SERP reads like a reseller who does not
 * stock the real thing, and French takes no capital on "végétales". A name with intentional
 * capitals is left exactly as the catalogue holds it; a SHOUTING one, or one typed entirely in
 * lower case, still gets the full treatment.
 */
function needsRecasing(name: string): boolean {
  const upper = name.match(/\p{Lu}/gu)?.length ?? 0;
  const lower = name.match(/\p{Ll}/gu)?.length ?? 0;
  if (!upper && !lower) return false;
  return lower === 0 || upper > lower;
}

/** "2.27KG" → "2,27 kg", "300G" → "300 g", "60CAPS" → "60 caps": French units, a space, a comma. */
function normalizeUnits(name: string): string {
  return name
    .replace(/(\d+)[.,](\d+)\s*(KG|G|GR|ML|L|MG)\b/gi, (m, a, b, u) => `${a},${b} ${u.toLowerCase().replace(/^gr$/, 'g')}`)
    .replace(/(\d+)\s*(KG|GR|ML|MG)\b/gi, (m, a, u) => `${a} ${u.toLowerCase().replace(/^gr$/, 'g')}`)
    /* `i` + the lookbehind added 24/09/2026: the rule was uppercase-only, so the catalogue's
       lowercase "GSN - CREATINE MONOHYDRATE | 200g" kept its glued unit into the <title> — live
       at position 7.0 on 272 impressions and 0 clicks. The lookbehind keeps the space out of the
       middle of a token that merely ends in digits ("B12g" is not "B12 g"). */
    .replace(/(?<![A-Za-z])(\d+)\s*[Gg]\b(?![A-Za-z])/g, '$1 g')
    .replace(/(\d+)\s*(CAPS|CAPSULES|GELULES|GÉLULES|TABS|TABLETS|COMPRIMES|COMPRIMÉS|SERVINGS|SOFTGELS?|DOSES|SACHETS)\b/gi,
      (m, a, u) => `${a} ${u.toLowerCase()}`);
}

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/*
 * ── DOUBLE-ENCODED UTF-8 IN THE CATALOGUE ────────────────────────────────────────────────────
 * Some imported names carry "â€“" for "–" and "Ã©" for "é": UTF-8 bytes that were read as
 * Latin-1 once and re-encoded. Live on 21/09/2026: the ISO 100 page titled itself
 * "ISO 100 DYMATIZE â€“ 2.3KG". Beyond looking broken in the SERP, the junk token defeats every
 * name comparison here (the humanizer, the auto-title detector, the formulaic-description
 * detector), so the page keeps its boilerplate snippet. Decode it back at the entry points.
 */
const MOJIBAKE = /[ÃÂ][-¿]|â€|Ã©|Ã¨|Ã |Ã§/;
/** The CP1252 0x80–0x9F block, which is where "â€“" gets its "€": reversed here, byte by byte. */
const CP1252_TO_BYTE: Record<number, number> = {
  0x20ac: 0x80, 0x201a: 0x82, 0x0192: 0x83, 0x201e: 0x84, 0x2026: 0x85, 0x2020: 0x86, 0x2021: 0x87,
  0x02c6: 0x88, 0x2030: 0x89, 0x0160: 0x8a, 0x2039: 0x8b, 0x0152: 0x8c, 0x017d: 0x8e, 0x2018: 0x91,
  0x2019: 0x92, 0x201c: 0x93, 0x201d: 0x94, 0x2022: 0x95, 0x2013: 0x96, 0x2014: 0x97, 0x02dc: 0x98,
  0x2122: 0x99, 0x0161: 0x9a, 0x203a: 0x9b, 0x0153: 0x9c, 0x017e: 0x9e, 0x0178: 0x9f,
};
/** A UTF-8 lead-byte character (Ã, Â, â…) followed by 1–3 continuation-range characters. */
const MOJIBAKE_RUN = new RegExp(
  '(?:[\\u00C2-\\u00F4][\\u0080-\\u00BF' +
    Object.keys(CP1252_TO_BYTE).map((c) => '\\u' + Number(c).toString(16).padStart(4, '0')).join('') +
    ']{1,3})+',
  'g',
);
/**
 * Repairs mojibake RUN BY RUN, because real strings are mixed: the backend appends a genuine "–"
 * to a name that carries "â€“". Whole-string decoding fails on the genuine dash (a lone 0x96 is
 * not UTF-8), so each candidate run is decoded on its own; a run that is not valid UTF-8 — e.g. a
 * genuine "é" that happens to precede "®" — is left exactly as it was.
 */
export function repairMojibake(s: string | null | undefined): string {
  if (!s) return '';
  if (!MOJIBAKE.test(s)) return s;
  const decoder = new TextDecoder('utf-8', { fatal: true });
  return s.replace(MOJIBAKE_RUN, (run) => {
    const bytes: number[] = [];
    for (const ch of run) {
      const c = ch.codePointAt(0) ?? 0;
      bytes.push(c < 0x100 ? c : CP1252_TO_BYTE[c]);
    }
    try {
      return decoder.decode(Uint8Array.from(bytes));
    } catch {
      return run;
    }
  });
}

/**
 * When the catalogue name only PARTLY led a sentence ("100% CREATINE MONOHYDRATE" matched,
 * "300G - BIOTECH USA de…" remained), re-prefixing the full human name would repeat the tail
 * ("…300 g 300 g de Biotech USA…" was live). Drop from the remainder whatever the human name
 * already ends with, compared space- and case-insensitively so "300G" and "300 g" agree.
 */
function dedupeSeam(human: string, rest: string): string {
  const flat = (t: string) => t.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/[^a-z0-9%]+/g, '');
  const h = flat(human);
  const tokens = rest.split(/\s+/);
  for (let k = Math.min(tokens.length, 8); k >= 1; k--) {
    const pre = flat(tokens.slice(0, k).join(' '));
    if (pre && h.endsWith(pre)) return tokens.slice(k).join(' ').replace(/^[\s\-–—:,.]+/u, '');
  }
  return rest;
}

/** Match a catalogue brand even when its record lists alternate names. */
function brandRe(brand: string): string {
  return brand.trim().split(/\s*\/\s*|\s{2,}/).filter(Boolean)
    .map((part) => part.trim().split(/\s+/).map(escapeRe).join('\\s*'))
    .join('|');
}

function nameSeparator(name: string, brand: string): string {
  const brandAtStart = brand ? new RegExp(`^(?:${brandRe(brand)})(?:\\b|$)`, 'i') : null;
  const brandAtEnd = brand ? new RegExp(`(?:^|\\s)(?:${brandRe(brand)})$`, 'i') : null;
  return name.replace(/\s+-\s+/g, (separator, offset: number) => {
    const before = name.slice(0, offset);
    const after = name.slice(offset + separator.length);
    const left = before.match(/\S+$/)?.[0] ?? '';
    const right = after.match(/^\S+/)?.[0] ?? '';
    if ((/^[a-z]$/i.test(left) && !/^[gl]$/i.test(left))
      || (/^[a-z]$/i.test(right) && !/^[gl]$/i.test(right))) return '-';
    if (/^\d+(?:[,.]\d+)?\s*(?:kg|g|mg|ml|caps|capsules?|gélules?|comprimés?|tablets?|servings|doses)\b/i.test(after)
      || (brandAtStart && brandAtEnd && (brandAtEnd.test(before) || brandAtStart.test(after)))) return ' – ';
    return separator;
  });
}

/** The product name the way a person would write it in a search box. Brand stripped from the tail. */
export function humanizeProductName(rawName: string, brand?: string | null): string {
  let name = normalizeUnits(repairMojibake(rawName).replace(/\s+/g, ' ').trim());
  if (brand?.trim()) {
    const b = `(?:${brandRe(brand)})`;
    name = name.replace(new RegExp(`\\s*[-–—|:]\\s*${b}\\s*$`, 'i'), '').replace(new RegExp(`\\s+${b}\\s*$`, 'i'), '');
  }
  name = name.replace(/\s*[-–—|:]+\s*$/, '').replace(/\s*[|]\s*/g, ' – ');
  name = nameSeparator(name, brand ?? '').trim();
  // When an imported name has both a brand and a format segment, repeated separators turn
  // the product into a dash chain before the price suffix is even added. Keep the words in order.
  const startsWithBrand = brand?.trim() && new RegExp(`^(?:${brandRe(brand)})(?:\\b|$)`, 'i').test(name);
  if (/\s+-\s+/.test(rawName) && (name.match(/ – /g) ?? []).length >= 2 && !startsWithBrand) {
    name = name.replace(/ – /g, ' ');
  }
  // Units, mojibake, the brand tail and the separators above are casing-independent repairs and
  // apply to every name. The token caser only runs where the catalogue carries no intent to keep.
  if (!needsRecasing(repairMojibake(rawName))) return name.replace(/\s{2,}/g, ' ').trim();
  return name.split(' ').map((t, i) => caseToken(t, i === 0)).join(' ').replace(/\s{2,}/g, ' ').trim();
}

function nameContainsBrand(name: string, brand: string): boolean {
  return new RegExp(`(?:^|[^\\p{L}\\p{N}])(?:${brandRe(brand)})(?=$|[^\\p{L}\\p{N}])`, 'iu').test(name);
}

/**
 * The product's heading — H1 and Product.name — in the same humanised form as its <title>:
 * "Serious Mass 5,45 kg – Optimum Nutrition", not the wholesaler string "SERIOUS MASS  5,45 KG -
 * OPTIMUM NUTRITION" (double space included) that both still carried on 28/09/2026 while the
 * <title> above them had been humanised. The shopper H1 is uppercased by CSS, so the screen does
 * not change; the text Google reads does. The brand stays when the name does not already carry it.
 */
export function humanProductHeading(product: Pick<Product, 'designation_fr' | 'slug' | 'brand'>): string {
  const raw = product.designation_fr ?? product.slug ?? 'Produit';
  const brandRaw = product.brand?.designation_fr?.trim() || '';
  const name = humanizeProductName(raw, brandRaw);
  if (!name) return raw;
  const brand = brandRaw ? humanizeProductName(brandRaw) : '';
  return brand && !nameContainsBrand(name, brandRaw) ? `${name} – ${brand}` : name;
}

/** The SERP budget for a product `<title>`. Google renders ~600 px; 65 characters is the width
 * this catalogue's titles were shortened to since the builder was written. */
const TITLE_MAX = 65;

/** Below this, the shortened name stops saying which product it is, so the brand tail goes first. */
const MIN_NAME_CHARS = 16;

/** The format segment at the very end of a name: "300 g", "– 60 caps", "5 mg". */
const FORMAT_TAIL = /(?:\s*[–|-]\s*)?\d+(?:[,.]\d+)?\s*(?:kg|g|mg|ml|caps|capsules?|gélules?|comprimés?|tablets?|servings|doses)\b$/i;

/**
 * Tidy the seam a truncation leaves behind. Three shapes, all seen in the 29/09 measurement:
 * a dangling connector ("Buffered Vitamin C with"), a trailing separator or comma ("EarthSweet
 * Chewables,") and an orphaned bare number where the unit was cut away ("Korean Ginseng – 100").
 * The number is only dropped when a separator introduced it, so "Zumub Omega 3" keeps its 3.
 */
function trimTitleSeam(text: string): string {
  let out = text.trim();
  let previous = '';
  while (out !== previous) {
    previous = out;
    out = out
      .replace(/\s*[–—|,;:-]\s*\d+(?:[,.]\d+)?$/u, '')
      .replace(/\s+(?:de|du|des|en|à|et|pour|avec|sans|plus|and|with|for|the|of)$/i, '')
      .replace(/\s+[+&]$/, '')
      .replace(/[\s–—|,;:-]+$/u, '')
      .trim();
  }
  return out;
}

/**
 * Shorten a humanised name so `name + suffix` fits TITLE_MAX, keeping the format segment
 * ("300 g", "60 caps") that tells the shopper which variant this is — it is the last thing to
 * drop, not the first, because the format is what Tunisians type ("creatine prix tunisie 500g").
 * Words are removed whole, from the end, until the assembled title actually fits; the previous
 * arithmetic estimated the budget once and overshot it by up to six characters.
 */
function fitTitleName(name: string, suffix: string): string {
  if (`${name}${suffix}`.length <= TITLE_MAX) return name;
  const budget = Math.max(TITLE_MAX - suffix.length, 0);
  const formatMatch = name.match(FORMAT_TAIL)?.[0] ?? '';
  const format = formatMatch.trim().replace(/^[–|-]\s*/, '');
  const keep = format ? ` – ${format}` : '';
  let head = trimTitleSeam(name.slice(0, name.length - formatMatch.length));
  while (head && `${head}${keep}`.length > budget) {
    const shorter = trimTitleSeam(head.replace(/\s+\S*$/, ''));
    if (shorter === head) break;
    head = shorter;
  }
  if (head && `${head}${keep}`.length <= budget) return `${head}${keep}`;
  // The format no longer fits beside the name: the name is what identifies the product, so it wins.
  if (head && head.length <= budget) return head;
  // A single word longer than the whole budget — keep it rather than emit an empty title.
  return trimTitleSeam(name.split(' ')[0]) || name;
}

/**
 * "{Human name} – Prix Tunisie | {Brand}", trimmed to a SERP-safe length.
 *
 * The trim used to reach only ONE of the three tails this builds. A product whose name already
 * carries its brand returned early, and a product with no brand at all returned after the length
 * test, so both skipped the shortening below entirely — measured 29/09/2026 by running this
 * builder over all 11,353 catalogue products, 3,240 of them (28.5 %) shipped a `<title>` past 65
 * characters, the worst 169 ("Sambucus
 * Black Elderberry Immune Complex Plus Vitamin C & Zinc, Natural Mixed Berry, 60 Chewable
 * Tablets – …"). Google truncates those to ~60 characters, so the format and the price words at
 * the end — the part that answers the query — never reached the SERP. The budget is now applied
 * to every path by `fitTitleName`, which is the same computation the brand path already did:
 * a title that already fits is returned byte-identical. Not one in-stock product and not one page
 * under the 05/10 freeze changes: every title this shortens belongs to an out-of-stock imported
 * product. `humanProductHeading` is deliberately NOT capped — an H1 has no SERP budget, and the
 * title/H1 difference this leaves is the ordinary one, not the three-different-names defect.
 */
export function humanProductTitle(product: Product): string {
  const raw = product.designation_fr ?? product.slug ?? 'Produit';
  const brandRaw = product.brand?.designation_fr?.trim() || '';
  const name = humanizeProductName(raw, brandRaw);
  const brand = brandRaw ? humanizeProductName(brandRaw) : '';
  // Three tails, unchanged: the brand when the name does not already say it, the shop when there
  // is no brand at all and it fits, nothing otherwise.
  const brandTail = brand && !nameContainsBrand(name, brandRaw) ? ` | ${brand}` : '';
  const shopTail = !brandRaw && `${name} – Prix Tunisie | Protein.tn`.length <= TITLE_MAX ? ' | Protein.tn' : '';
  let suffix = ` – Prix Tunisie${brandTail || shopTail}`;
  // A very long brand would leave no room for the product itself; the tail is the optional half.
  if (TITLE_MAX - suffix.length < MIN_NAME_CHARS) suffix = ' – Prix Tunisie';
  return `${fitTitleName(name, suffix)}${suffix}`;
}

const TITLE_SUFFIX_WORDS = new Set(['prix', 'tunisie', 'livraison', 'rapide', 'proteine', 'protein', 'tn', 'et', 'and', 'en', 'ligne', 'pas', 'cher', 'meilleur', 'achat', 'acheter', 'boutique']);

/**
 * True when a stored title is just the raw catalogue name plus boilerplate — the backend's own
 * default, not something a person wrote. Those are rewritten; a human title is left alone.
 */
export function isAutoGeneratedTitle(explicit: string, rawName: string): boolean {
  const e = normalize(repairMojibake(explicit));
  const n = normalize(repairMojibake(rawName));
  if (!n || !e.startsWith(n)) return false;
  const rest = e.slice(n.length).trim();
  return rest === '' || rest.split(' ').every((w) => TITLE_SUFFIX_WORDS.has(w));
}

/** Reserve the price first; never cut a word (including unusually long unbroken tokens). */
function enrichDescription(product: Product, productName: string): string {
  const price = getPriceDisplay(product).finalPrice;
  const suffix = price > 0 && Number.isFinite(price) ? ` Prix : ${formatTnd(price)}.` : '';
  // Skip section labels and title headings; the paragraphs/list items carry the real copy.
  const body = (product.description_fr ?? '')
    .replace(/<h[1-6]\b[^>]*>[\s\S]*?<\/h[1-6]\s*>/gi, ' ')
    .replace(/<\/(?:li|p)>/gi, '. ');
  const plain = buildMetaDescription(body, { maxLen: Infinity })
    /* `,` added 09/09/2026: the CMS copy contains "créatine monohydrate pure micronisée ," and
       "Gainer hautement calorique ,", and that space survived into the live snippet. French takes
       no space before a comma (unlike ; : ! ?), so this is a typo in the source, not a
       typographic convention to preserve. Only the comma is added here — the existing set is left
       exactly as it was. */
    .replace(/\s+([.!?,])/g, '$1').replace(/(?:\.\s*){2,}/g, '. ')
    .replace(/([!?])\./g, '$1')
    .split(/(?<=[.!?])\s+/)
    .map((sentence) => {
      /*
       * The catalogue name often opens the sentence as its SUBJECT. The previous pass deleted it to
       * avoid echoing the title, and left "Est présentée comme une whey…", "De BioTechUSA est une
       * whey…" and "300 g de Biotech USA est une créatine…" in the live snippets (a partial match
       * ate half the name). Keep the subject — as the human-cased name the <title> now uses — so
       * the snippet is a sentence that leads with the query term, which is what Google bolds.
       */
      const brand = product.brand?.designation_fr?.trim();
      const human = humanizeProductName(productName, brand);
      const restAfterName = withoutLeadingName(sentence, productName, true);
      let fact: string;
      if (restAfterName !== sentence) {
        if (!restAfterName.trim()) return ''; // the sentence WAS the name (a heading line)
        fact = `${human} ${dedupeSeam(human, restAfterName)}`.trim();
      } else if (brand) {
        const restAfterBrand = withoutLeadingName(sentence, brand, true);
        fact = restAfterBrand !== sentence && restAfterBrand.trim()
          ? `${humanizeProductName(brand)} ${restAfterBrand}`
          : sentence;
      } else {
        fact = sentence;
      }
      return fact ? fact[0].toUpperCase() + fact.slice(1) : '';
    }).filter(Boolean).join(' ').trim();
  const budget = 160 - suffix.length;
  let excerpt = plain;
  if (excerpt.length > budget) {
    const window = excerpt.slice(0, budget - 1);
    /*
     * ── PREFER A CLAUSE BOUNDARY. A WORD BOUNDARY IS NOT ENOUGH ─────────────────────────────
     * Cutting on the last space is word-safe and still produces a broken sentence. Measured live
     * on /omega-3/omega-3-fish-oil-240-softgel-weightworld — the biggest zero-CTR line in the
     * whole Search Console export, 2,827 impressions on `omega 3 fish oil` at position 7.5 and
     * 3,475 on the page at 0.75%:
     *
     *   "…riche en EPA et DHA, deux acides gras essentiels reconnus pour leurs… Prix : 179 DT."
     *
     * It ends on a possessive with nothing to possess. Every word is whole and the sentence is
     * still nonsense, which is worse than a hard cut because it reads as a fault in the product
     * rather than a fault in the truncation.
     *
     * So: take the last sentence end inside the budget when it leaves at least 55% of the
     * available characters used — a complete sentence needs no ellipsis and reads as deliberate.
     * Below that threshold the sentence is too short to be worth the lost characters, and the
     * word-boundary cut with an ellipsis stays as the fallback. The `.` in the lookbehind is
     * excluded when it follows a digit so a dose ("1,5 g.") or a decimal cannot end the snippet
     * on half a fact.
     */
    const MIN_CLAUSE_RATIO = 0.55;
    const clause = Math.max(
      window.lastIndexOf('. '),
      window.lastIndexOf('! '),
      window.lastIndexOf('? ')
    );
    const clauseUsable =
      clause > 0 &&
      clause + 1 >= Math.floor(budget * MIN_CLAUSE_RATIO) &&
      !/\d\s*$/.test(window.slice(0, clause));

    /*
     * Tier 2, added in the same pass after measuring tier 1: a comma or semicolon.
     *
     * The sentence tier fixed /whey-proteine/100-whey-gold-standard-2-27kg, whose first sentence
     * ends inside the budget. It did nothing for the omega-3 page this was written for, because
     * that copy's FIRST sentence is longer than 160 characters — there is no sentence end to
     * find, so it fell straight through to the word cut and still read "reconnus pour leurs…".
     *
     * A comma is not a sentence, so the ellipsis stays. But "…riche en EPA et DHA…" is a whole
     * idea and "…reconnus pour leurs…" is not, and that is the difference the reader sees.
     */
    const softClause = Math.max(window.lastIndexOf(', '), window.lastIndexOf('; '));
    const softUsable =
      !clauseUsable &&
      softClause > 0 &&
      softClause >= Math.floor(budget * MIN_CLAUSE_RATIO) &&
      !/\d\s*$/.test(window.slice(0, softClause));

    if (clauseUsable) {
      excerpt = window.slice(0, clause + 1);
    } else if (softUsable) {
      excerpt = `${window.slice(0, softClause)}…`;
    } else {
      const boundary = /\s/.test(excerpt[budget - 1]) ? window.length : window.lastIndexOf(' ');
      excerpt = boundary > 0 ? `${window.slice(0, boundary).replace(/[\s,;:.–—-]+$/u, '')}…` : '';
    }
  }
  return `${excerpt || 'Consultez la composition et les conseils d’utilisation sur la fiche produit.'}${suffix}`;
}

/**
 * Meta description: benefit + authenticity + delivery + location (Tunisie). Max 160 chars.
 *
 * Two defects fixed here, both visible in live search results:
 *
 * 1. `.replace(/&[a-z]+;/gi, ' ')` DELETED entities instead of decoding them, so
 *    "MUSCULAIRE &amp; PERFORMANCE" reached Google as "MUSCULAIRE   PERFORMANCE" — the word
 *    silently gone. This is the same bug fixed for categories in #192 and blog posts in #195;
 *    this path was the last one still carrying it. `buildMetaDescription` decodes properly.
 * 2. `.slice(0, 160)` cut mid-word. Google appends its own ellipsis to long descriptions, so a
 *    snippet ending on half a word is damage we inflicted, not Google.
 *
 * It also drops a leading repetition of the product name, which the CMS copy almost always opens
 * with — that name is already the title on the line above, so restating it burned ~40 characters
 * of a 160-character budget.
 */
export function productDescription(product: Product, rawProductName: string): string {
  const productName = repairMojibake(rawProductName);
  const explicit = repairMojibake(product.seo?.description || product.seo_description || product.meta_description || product.meta_description_fr);
  if (explicit?.trim()) {
    /*
     * Imported catalogue templates are valid text but weak SERP copy: Omega 3 Fish Oil earned
     * 3,475 impressions at position 7.4 and only 0.75% CTR. Bringing scattered product facts
     * and price into the snippet makes those characters useful. Enrich formulaic identity +
     * shop copy only; hand-written benefit copy remains authoritative.
     */
    // A name-only explicit field can become empty after title removal; it still needs enrichment.
    if (isFormulaicProductDescription(explicit, product, productName)) return enrichDescription(product, productName);
    const plain = buildMetaDescription(explicit, { title: productName, maxLen: 160 });
    if (plain) return plain;
  }
  // Preserve the pre-existing non-template fallback behavior.
  const plain = buildMetaDescription(product.description_fr, { title: productName, maxLen: 90 });
  if (plain) return `${plain} Prix Tunisie. Livraison ${DELIVERY.windowLabel}. Protéine Tunisie.`;
  return `Acheter ${productName} en Tunisie – Meilleur prix, livraison rapide, produits authentiques. Sousse, Tunis, toute la Tunisie. Protéine Tunisie.`;
}

/**
 * SHARED WITH THE CRAWLER ROUTE ON PURPOSE.
 *
 * `x-crawler/product/[...slug]` is what middleware rewrites a bot to, and it used to build its
 * own title from `product.seo.title`. So the curated map below — assembled from a Search Console
 * export precisely to raise CTR — was served to browsers and never to Google. Measured on
 * 08/09/2026, the same URL answered differently by user agent:
 *
 *   browser   "Omega 3 Fish Oil WeightWorld 240 capsules – Prix Tunisie"   (the curated one)
 *   Googlebot "Omega 3 fish oil 240 softgel - weightworld – Prix Tunisie"  (the backend's)
 *
 * Both routes now call this, so a title change cannot reach one audience and miss the other.
 */
export function productTitle(product: Product): string {
  /*
   * Search Console opportunity titles (3-month export, 31/08/2026).
   *
   * These are deliberately limited to products with meaningful impressions where the imported
   * catalogue title does not answer the actual query.  They do not invent discounts, stock or
   * delivery promises; price and availability remain in Product/Offer structured data.  Keeping
   * this as a small reviewed map also avoids turning every PDP into the same keyword template.
   */
  const searchOpportunityTitles: Record<string, string> = {
    'omega-3-fish-oil-240-softgel-weightworld':
      'Omega 3 Fish Oil WeightWorld 240 capsules – Prix Tunisie',
    '100-whey-gold-standard-2-27kg':
      'Gold Standard Whey 2,27 kg – Prix Tunisie | Protein.tn',
    'anabolic-whey-80-2-25kg-proactive':
      'Anabolic Whey 80 ProActive 2,25 kg – Prix Tunisie',
    'serious-mass-2-7-kg':
      'Serious Mass 2,7 kg – Prix Tunisie | Optimum Nutrition',
    'serious-mass-5-45-kg-optimum-nutrition':
      'Serious Mass 5,45 kg – Prix Tunisie | Optimum Nutrition',
    // Keyword research 28/09/2026 (GSC 3 m): "straps tunisie" 206 + "straps prix tunisie" 123 impr at
    // ~7.5 with ~0 % CTR, answered by two shouting PDPs that competed for the same word. Each now owns
    // its own term. "arginine prix tunisie" 49 + "l-arginine prix tunisie" 34 hit a title without
    // "L-Arginine" (and with the Spanish "Capsulas"). All three in stock.
    'lifting-straps': 'Straps de musculation (lifting straps) – Prix Tunisie',
    'bandes-de-tirage': 'Bandes de tirage musculation – Prix Tunisie',
    'elite-arginine-120-capsulas': 'Elite L-Arginine 120 gélules – Prix Tunisie | Scenit',
    // The builder's shortening dropped 'incliné' — the one word that says which bench this is.
    'banc-de-musculation-developpe-incline': 'Banc développé incliné MND Fitness – Prix Tunisie',
    // Named SFD Nutrition but filed under Real Pharm (fixed by migration 2026_09_29_000100); the title
    // must not carry the wrong maker meanwhile.
    'vitamin-complex-sport-120-tablets-sfd-nutrition': 'Vitamin Complex Sport+ SFD 120 comprimés – Prix Tunisie',
    // Reviewed 29/09/2026: in-stock PDPs whose title still needs product-specific wording.
    'magnesium-bisglycinate-vitamine-b6-1422mg-weightworld':
      'Magnésium Bisglycinate WeightWorld 180 caps – Prix Tunisie',
    't-9-testo-booster-120-caps': 'T9 Testo Booster 120 gélules – Prix Tunisie | Scenit',
    'one-a-day-biotech-usa': 'One-A-Day 100 comprimés – Prix Tunisie | Biotech USA',
    'protein-shaker-450ml-sport-life': 'Shaker protéine Sport Life 450 ml – Prix Tunisie',
    'vegan-vitamin-d3-k2-365-tablets-weightworld':
      'Vitamine D3 + K2 WeightWorld 365 comprimés – Prix Tunisie',
    'gold-creatine-kevin-levrone-300-g': 'Gold Creatine 300 g – Prix Tunisie | Kevin Levrone',
    'whey-testo-mr-x-1-8-kg-v-shapes': 'Whey Testo MR.X 1,8 kg – Prix Tunisie | V-Shape Supps',
    'micronised-creatine-optimum-nutrition-317g':
      'Micronised Creatine 317 g – Prix Tunisie | Optimum Nutrition',
    'lipo-6-black-ultra-concentrate-60caps':
      'Lipo 6 Black Ultra Concentrate Nutrex 60 caps – Prix Tunisie',
    'multivitamines-et-mineraux-400-tablets-weightword':
      'Multivitamines WeightWorld 400 comprimés – Prix Tunisie',
    'creatine-monohydrate-ostrovit-500gr': 'Créatine Monohydrate OstroVit 500 g – Prix Tunisie',
    'creatine-real-pharm-300g': 'Créatine Monohydrate Real Pharm 300 g – Prix Tunisie',
    'whey-iso-regime-2kg-william-bonac':
      'Whey Iso Regime 2 kg – Prix Tunisie | William Bonac',
    'pump-extreme-pre-workout-challenger-nutrition-30-servings':
      'Pump Extreme Pre-Workout Challenger 30 doses – Prix Tunisie',
    'ashwagandha-ksm-66-en-comprimes-180-1500-mg':
      'Ashwagandha KSM-66 WeightWorld 180 comprimés – Prix Tunisie',
    'carbo-plus-1kg-universal': 'Carbo Plus 1 kg – Prix Tunisie | Universal Nutrition',
    'hydro-whey-1-59-kg': 'Hydro Whey 1,59 kg – Prix Tunisie | Optimum Nutrition',
    'zumub-omega-3-90-caps': 'Zumub Oméga 3 90 capsules – Prix Tunisie',
    'tantor-whey-protein-2267-g-scenit-nutrition':
      'Tantor Whey Protein 2,27 kg – Prix Tunisie | Scenit',
    'vitamin-c-110-tabs-ostrovit':
      'Vitamine C 1000 mg OstroVit 110 comprimés – Prix Tunisie',
    'zumub-zinc-100-comprimes': 'Zumub Zinc 100 comprimés – Prix Tunisie',
  };
  const opportunityTitle = product.slug ? searchOpportunityTitles[product.slug] : undefined;
  if (opportunityTitle) return opportunityTitle;

  const explicit = repairMojibake(product.seo?.title || product.seo_title || product.meta_title);
  const name = repairMojibake(product.designation_fr ?? product.slug ?? 'Produit');
  // A title a person wrote in the CMS wins. The backend's own default ("RAW NAME – Prix Tunisie")
  // is boilerplate on top of a shouting catalogue name, and is rewritten like the rest.
  if (explicit?.trim() && !isAutoGeneratedTitle(explicit, name)) return explicit.trim();
  return humanProductTitle(product);
}
