import type { Product } from '@/types';
import { buildMetaDescription, htmlToText } from './sanitizeProductHtml';
import { formatTnd, getPriceDisplay } from './productPrice';

function normalize(text: string): string {
  return text.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase()
    .replace(/[^\p{L}\p{N}]+/gu, ' ').trim();
}

/** Imports vary punctuation and sometimes omit flavour/size tokens from the title. */
function withoutLeadingName(text: string, name: string, prose = false): string {
  const original = text;
  if (prose) text = text.replace(/^(?:(?:le|la|les|de|du)\s+|[ld][’'])/i, '');
  const nameWords = normalize(name).split(' ');
  const words = [...text.matchAll(/[\p{L}\p{N}]+/gu)];
  if (!words.length || normalize(words[0][0]) !== nameWords[0]) return original;
  let next = 0;
  let end = 0;
  let matched = 0;
  for (const word of words) {
    const normalized = normalize(word[0]);
    if (prose && matched > 0 && /^(?:de|d|du)$/.test(normalized)) continue;
    const at = nameWords.indexOf(normalized, next);
    if (at < 0) break;
    next = at + 1;
    end = word.index! + word[0].length;
    matched++;
  }
  if (matched < Math.min(prose ? 2 : 3, nameWords.length)) return original;
  return text.slice(end).replace(/^[\s\-–—:,.®™]+/u, '').trim();
}

/**
 * Classify the FULL explicit text, before its 160-character cut. Uniqueness is irrelevant:
 * remove identity and commerce-only clauses; any remaining words preserve the editor's copy.
 * Unlike a marker count, this keeps benefit copy even when followed by every delivery marker.
 * Identity values come from the product, so an arbitrary sentence after "marque" is not eaten.
 */
export function isFormulaicProductDescription(raw: string, product: Product, productName: string): boolean {
  let text = normalize(withoutLeadingName(htmlToText(raw, Infinity), productName));
  if (!normalize(raw)) return false;

  const identities = [
    product.brand?.designation_fr,
    product.sous_categorie?.designation_fr,
    product.sous_categorie?.categorie?.designation_fr,
    ...(product.sous_categories ?? []).flatMap((sub) => [sub.designation_fr, sub.categorie?.designation_fr]),
  ].filter((value): value is string => !!value).map(normalize).filter(Boolean);
  for (const identity of [...new Set(identities)].sort((a, b) => b.length - a.length)) {
    text = ` ${text} `.split(` ${identity} `).join(' ').trim();
  }
  const shopClauses = [
    /\bboutique de complements(?: alimentaires)? a sousse en tunisie\b/g,
    /\blivraison (?:24 72\s*h|rapide)(?: partout)?(?: en|dans toute la) tunisie\b/g,
    /\blivraison 24 72\s*h\b/g,
    /\bpaiement a la livraison\b/g,
    /\b(?:produits? )?(?:100 )?authentiques?\b/g,
    /\b(?:(?:sur|chez) )?(?:proteine tunisie|protein tn)\b/g,
    /\b(?:en vente |disponible )?en tunisie\b/g,
    /\bfiche produit du rayon\b/g,
    /\b(?:rayon|categorie|marque)\b/g,
    /\b\d+(?: \d+)? dt\b/g,
  ];
  for (const clause of shopClauses) text = text.replace(clause, ' ');
  return !text.trim();
}

/*
 * ── HUMAN PRODUCT NAMES, GLOBALLY ────────────────────────────────────────────────────────────
 * The catalogue stores product names the way a wholesaler types them: "100% CREATINE MONOHYDRATE
 * 300G - BIOTECH USA". Until 21/09/2026 that string was the <title> of almost every product page
 * (plus "– Prix Tunisie"), while the handful of pages an SEO pass had rewritten by hand
 * ("Serious Mass 5,45 kg – Prix Tunisie | Optimum Nutrition") were the ones that ranked. The
 * pattern of those hand rewrites is mechanical — sentence case, French units, brand moved to the
 * end — so it is applied here to every product instead of five. A title a human wrote in the CMS
 * still wins (see isAutoGeneratedTitle); only the auto-generated shouting ones are rewritten.
 */
const KEEP_UPPER = new Set([
  'USA', 'UK', 'EU', 'BCAA', 'BCAAS', 'EAA', 'EAAS', 'ZMA', 'HMB', 'CLA', 'MSM', 'ISO', 'XT', 'EFX',
  'HGH', 'ATP', 'GABA', 'CBD', 'MCT', 'XL', 'XXL', 'DHA', 'EPA', 'DAA', 'HCL', 'HCA', 'Q10', 'MK7',
  'ON', 'NO2', 'ZMB6', 'TNT', 'GH', 'L', 'D', 'C', 'E', 'K', 'B', 'A', 'MR.X', 'V8', 'C4', 'X',
]);
/** French function words stay lowercase inside a title (never as the first word). */
const FRENCH_SMALL = new Set(['de', 'du', 'des', 'la', 'le', 'les', 'et', 'en', 'à', 'a', 'au', 'aux', 'pour', 'avec', 'sans', 'sur', 'par', 'ou', 'un', 'une']);

/** Unit and count words that follow a number: always lowercase ("2,27 kg", "60 caps"). */
const UNIT_WORDS = new Set(['kg', 'g', 'gr', 'mg', 'ml', 'l', 'caps', 'capsules', 'gelules', 'gélules', 'tabs', 'tablets', 'comprimes', 'comprimés', 'servings', 'softgel', 'softgels', 'doses', 'sachets']);

function caseToken(token: string, first: boolean): string {
  if (!token) return token;
  const upper = token.toUpperCase();
  const lower = token.toLowerCase();
  if (KEEP_UPPER.has(upper)) return upper;
  if (UNIT_WORDS.has(lower)) return lower;
  if (/^[A-Z]\d+$/i.test(token)) return upper; // B6, D3, K2, C4
  if (/^[A-Z]{2,}\d+$/i.test(token)) return upper; // ISO100, NO2, C4
  if (/^\d/.test(token)) return lower.replace(/(\d)(kg|g|ml|l|mg)$/, (m, d, u) => d + u);
  if (token.includes('-')) return token.split('-').map((p, i) => caseToken(p, first && i === 0)).join('-');
  if (!first && FRENCH_SMALL.has(lower)) return lower;
  return lower.charAt(0).toUpperCase() + lower.slice(1);
}

/** "2.27KG" → "2,27 kg", "300G" → "300 g", "60CAPS" → "60 caps": French units, a space, a comma. */
function normalizeUnits(name: string): string {
  return name
    .replace(/(\d+)[.,](\d+)\s*(KG|G|GR|ML|L|MG)\b/gi, (m, a, b, u) => `${a},${b} ${u.toLowerCase().replace(/^gr$/, 'g')}`)
    .replace(/(\d+)\s*(KG|GR|ML|MG)\b/gi, (m, a, u) => `${a} ${u.toLowerCase().replace(/^gr$/, 'g')}`)
    .replace(/(\d+)\s*G\b(?![A-Za-z])/g, '$1 g')
    .replace(/(\d+)\s*(CAPS|CAPSULES|GELULES|GÉLULES|TABS|TABLETS|COMPRIMES|COMPRIMÉS|SERVINGS|SOFTGELS?|DOSES|SACHETS)\b/gi,
      (m, a, u) => `${a} ${u.toLowerCase()}`);
}

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/*
 * ── DOUBLE-ENCODED UTF-8 IN THE CATALOGUE ────────────────────────────────────────────────────
 * Some imported names carry "â€“" for "–" and "Ã©" for "é": UTF-8 bytes that were read as
 * Latin-1 once and re-encoded. Live on 21/09/2026: the ISO 100 page titled itself
 * "ISO 100 DYMATIZE â€“ 2.3KG". Beyond looking broken in the SERP, the junk token defeats every
 * name comparison here (the humanizer, the auto-title detector, the formulaic-description
 * detector), so the page keeps its boilerplate snippet. Decode it back at the entry points.
 */
const MOJIBAKE = /[ÃÂ][-¿]|â€|Ã©|Ã¨|Ã |Ã§/;
/** The CP1252 0x80–0x9F block, which is where "â€“" gets its "€": reversed here, byte by byte. */
const CP1252_TO_BYTE: Record<number, number> = {
  0x20ac: 0x80, 0x201a: 0x82, 0x0192: 0x83, 0x201e: 0x84, 0x2026: 0x85, 0x2020: 0x86, 0x2021: 0x87,
  0x02c6: 0x88, 0x2030: 0x89, 0x0160: 0x8a, 0x2039: 0x8b, 0x0152: 0x8c, 0x017d: 0x8e, 0x2018: 0x91,
  0x2019: 0x92, 0x201c: 0x93, 0x201d: 0x94, 0x2022: 0x95, 0x2013: 0x96, 0x2014: 0x97, 0x02dc: 0x98,
  0x2122: 0x99, 0x0161: 0x9a, 0x203a: 0x9b, 0x0153: 0x9c, 0x017e: 0x9e, 0x0178: 0x9f,
};
/** A UTF-8 lead-byte character (Ã, Â, â…) followed by 1–3 continuation-range characters. */
const MOJIBAKE_RUN = new RegExp(
  '(?:[\\u00C2-\\u00F4][\\u0080-\\u00BF' +
    Object.keys(CP1252_TO_BYTE).map((c) => '\\u' + Number(c).toString(16).padStart(4, '0')).join('') +
    ']{1,3})+',
  'g',
);
/**
 * Repairs mojibake RUN BY RUN, because real strings are mixed: the backend appends a genuine "–"
 * to a name that carries "â€“". Whole-string decoding fails on the genuine dash (a lone 0x96 is
 * not UTF-8), so each candidate run is decoded on its own; a run that is not valid UTF-8 — e.g. a
 * genuine "é" that happens to precede "®" — is left exactly as it was.
 */
export function repairMojibake(s: string | null | undefined): string {
  if (!s) return '';
  if (!MOJIBAKE.test(s)) return s;
  const decoder = new TextDecoder('utf-8', { fatal: true });
  return s.replace(MOJIBAKE_RUN, (run) => {
    const bytes: number[] = [];
    for (const ch of run) {
      const c = ch.codePointAt(0) ?? 0;
      bytes.push(c < 0x100 ? c : CP1252_TO_BYTE[c]);
    }
    try {
      return decoder.decode(Uint8Array.from(bytes));
    } catch {
      return run;
    }
  });
}

/**
 * When the catalogue name only PARTLY led a sentence ("100% CREATINE MONOHYDRATE" matched,
 * "300G - BIOTECH USA de…" remained), re-prefixing the full human name would repeat the tail
 * ("…300 g 300 g de Biotech USA…" was live). Drop from the remainder whatever the human name
 * already ends with, compared space- and case-insensitively so "300G" and "300 g" agree.
 */
function dedupeSeam(human: string, rest: string): string {
  const flat = (t: string) => t.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/[^a-z0-9%]+/g, '');
  const h = flat(human);
  const tokens = rest.split(/\s+/);
  for (let k = Math.min(tokens.length, 8); k >= 1; k--) {
    const pre = flat(tokens.slice(0, k).join(' '));
    if (pre && h.endsWith(pre)) return tokens.slice(k).join(' ').replace(/^[\s\-–—:,.]+/u, '');
  }
  return rest;
}

/** A brand regex tolerant of the catalogue's "BIOTECHUSA" / "BIOTECH USA" spelling drift. */
function brandRe(brand: string): string {
  return brand.trim().split(/\s+/).map(escapeRe).join('\\s*');
}

/** The product name the way a person would write it in a search box. Brand stripped from the tail. */
export function humanizeProductName(rawName: string, brand?: string | null): string {
  let name = normalizeUnits(repairMojibake(rawName).replace(/\s+/g, ' ').trim());
  if (brand?.trim()) {
    const b = brandRe(brand);
    name = name.replace(new RegExp(`\\s*[-–—|:]\\s*${b}\\s*$`, 'i'), '').replace(new RegExp(`\\s+${b}\\s*$`, 'i'), '');
  }
  name = name.replace(/\s*[-–—|:]+\s*$/, '').replace(/\s*[|]\s*/g, ' – ').replace(/\s+-\s+/g, ' – ').trim();
  return name.split(' ').map((t, i) => caseToken(t, i === 0)).join(' ').replace(/\s{2,}/g, ' ').trim();
}

function nameContainsBrand(name: string, brand: string): boolean {
  return new RegExp(brandRe(brand), 'i').test(name);
}

/** "{Human name} – Prix Tunisie | {Brand}", trimmed to a SERP-safe length. */
export function humanProductTitle(product: Product): string {
  const raw = product.designation_fr ?? product.slug ?? 'Produit';
  const brandRaw = product.brand?.designation_fr?.trim() || '';
  const name = humanizeProductName(raw, brandRaw);
  const brand = brandRaw ? humanizeProductName(brandRaw) : '';
  const base = `${name} – Prix Tunisie`;
  const tail = brand && !nameContainsBrand(name, brand) ? brand : 'Protein.tn';
  const full = `${base} | ${tail}`;
  return full.length <= 65 ? full : base;
}

const TITLE_SUFFIX_WORDS = new Set(['prix', 'tunisie', 'livraison', 'rapide', 'proteine', 'protein', 'tn', 'et', 'and', 'en', 'ligne', 'pas', 'cher', 'meilleur', 'achat', 'acheter', 'boutique']);

/**
 * True when a stored title is just the raw catalogue name plus boilerplate — the backend's own
 * default, not something a person wrote. Those are rewritten; a human title is left alone.
 */
export function isAutoGeneratedTitle(explicit: string, rawName: string): boolean {
  const e = normalize(repairMojibake(explicit));
  const n = normalize(repairMojibake(rawName));
  if (!n || !e.startsWith(n)) return false;
  const rest = e.slice(n.length).trim();
  return rest === '' || rest.split(' ').every((w) => TITLE_SUFFIX_WORDS.has(w));
}

/** Reserve the price first; never cut a word (including unusually long unbroken tokens). */
function enrichDescription(product: Product, productName: string): string {
  const price = getPriceDisplay(product).finalPrice;
  const suffix = price > 0 && Number.isFinite(price) ? ` Prix : ${formatTnd(price)}.` : '';
  // Skip section labels and title headings; the paragraphs/list items carry the real copy.
  const body = (product.description_fr ?? '')
    .replace(/<h[1-6]\b[^>]*>[\s\S]*?<\/h[1-6]\s*>/gi, ' ')
    .replace(/<\/(?:li|p)>/gi, '. ');
  const plain = buildMetaDescription(body, { maxLen: Infinity })
    /* `,` added 09/09/2026: the CMS copy contains "créatine monohydrate pure micronisée ," and
       "Gainer hautement calorique ,", and that space survived into the live snippet. French takes
       no space before a comma (unlike ; : ! ?), so this is a typo in the source, not a
       typographic convention to preserve. Only the comma is added here — the existing set is left
       exactly as it was. */
    .replace(/\s+([.!?,])/g, '$1').replace(/(?:\.\s*){2,}/g, '. ')
    .replace(/([!?])\./g, '$1')
    .split(/(?<=[.!?])\s+/)
    .map((sentence) => {
      /*
       * The catalogue name often opens the sentence as its SUBJECT. The previous pass deleted it to
       * avoid echoing the title, and left "Est présentée comme une whey…", "De BioTechUSA est une
       * whey…" and "300 g de Biotech USA est une créatine…" in the live snippets (a partial match
       * ate half the name). Keep the subject — as the human-cased name the <title> now uses — so
       * the snippet is a sentence that leads with the query term, which is what Google bolds.
       */
      const brand = product.brand?.designation_fr?.trim();
      const human = humanizeProductName(productName, brand);
      const restAfterName = withoutLeadingName(sentence, productName, true);
      let fact: string;
      if (restAfterName !== sentence) {
        if (!restAfterName.trim()) return ''; // the sentence WAS the name (a heading line)
        fact = `${human} ${dedupeSeam(human, restAfterName)}`.trim();
      } else if (brand) {
        const restAfterBrand = withoutLeadingName(sentence, brand, true);
        fact = restAfterBrand !== sentence && restAfterBrand.trim()
          ? `${humanizeProductName(brand)} ${restAfterBrand}`
          : sentence;
      } else {
        fact = sentence;
      }
      return fact ? fact[0].toUpperCase() + fact.slice(1) : '';
    }).filter(Boolean).join(' ').trim();
  const budget = 160 - suffix.length;
  let excerpt = plain;
  if (excerpt.length > budget) {
    const window = excerpt.slice(0, budget - 1);
    /*
     * ── PREFER A CLAUSE BOUNDARY. A WORD BOUNDARY IS NOT ENOUGH ─────────────────────────────
     * Cutting on the last space is word-safe and still produces a broken sentence. Measured live
     * on /omega-3/omega-3-fish-oil-240-softgel-weightworld — the biggest zero-CTR line in the
     * whole Search Console export, 2,827 impressions on `omega 3 fish oil` at position 7.5 and
     * 3,475 on the page at 0.75%:
     *
     *   "…riche en EPA et DHA, deux acides gras essentiels reconnus pour leurs… Prix : 179 DT."
     *
     * It ends on a possessive with nothing to possess. Every word is whole and the sentence is
     * still nonsense, which is worse than a hard cut because it reads as a fault in the product
     * rather than a fault in the truncation.
     *
     * So: take the last sentence end inside the budget when it leaves at least 55% of the
     * available characters used — a complete sentence needs no ellipsis and reads as deliberate.
     * Below that threshold the sentence is too short to be worth the lost characters, and the
     * word-boundary cut with an ellipsis stays as the fallback. The `.` in the lookbehind is
     * excluded when it follows a digit so a dose ("1,5 g.") or a decimal cannot end the snippet
     * on half a fact.
     */
    const MIN_CLAUSE_RATIO = 0.55;
    const clause = Math.max(
      window.lastIndexOf('. '),
      window.lastIndexOf('! '),
      window.lastIndexOf('? ')
    );
    const clauseUsable =
      clause > 0 &&
      clause + 1 >= Math.floor(budget * MIN_CLAUSE_RATIO) &&
      !/\d\s*$/.test(window.slice(0, clause));

    /*
     * Tier 2, added in the same pass after measuring tier 1: a comma or semicolon.
     *
     * The sentence tier fixed /whey-proteine/100-whey-gold-standard-2-27kg, whose first sentence
     * ends inside the budget. It did nothing for the omega-3 page this was written for, because
     * that copy's FIRST sentence is longer than 160 characters — there is no sentence end to
     * find, so it fell straight through to the word cut and still read "reconnus pour leurs…".
     *
     * A comma is not a sentence, so the ellipsis stays. But "…riche en EPA et DHA…" is a whole
     * idea and "…reconnus pour leurs…" is not, and that is the difference the reader sees.
     */
    const softClause = Math.max(window.lastIndexOf(', '), window.lastIndexOf('; '));
    const softUsable =
      !clauseUsable &&
      softClause > 0 &&
      softClause >= Math.floor(budget * MIN_CLAUSE_RATIO) &&
      !/\d\s*$/.test(window.slice(0, softClause));

    if (clauseUsable) {
      excerpt = window.slice(0, clause + 1);
    } else if (softUsable) {
      excerpt = `${window.slice(0, softClause)}…`;
    } else {
      const boundary = /\s/.test(excerpt[budget - 1]) ? window.length : window.lastIndexOf(' ');
      excerpt = boundary > 0 ? `${window.slice(0, boundary).replace(/[\s,;:.–—-]+$/u, '')}…` : '';
    }
  }
  return `${excerpt || 'Consultez la composition et les conseils d’utilisation sur la fiche produit.'}${suffix}`;
}

/**
 * Meta description: benefit + authenticity + delivery + location (Tunisie). Max 160 chars.
 *
 * Two defects fixed here, both visible in live search results:
 *
 * 1. `.replace(/&[a-z]+;/gi, ' ')` DELETED entities instead of decoding them, so
 *    "MUSCULAIRE &amp; PERFORMANCE" reached Google as "MUSCULAIRE   PERFORMANCE" — the word
 *    silently gone. This is the same bug fixed for categories in #192 and blog posts in #195;
 *    this path was the last one still carrying it. `buildMetaDescription` decodes properly.
 * 2. `.slice(0, 160)` cut mid-word. Google appends its own ellipsis to long descriptions, so a
 *    snippet ending on half a word is damage we inflicted, not Google.
 *
 * It also drops a leading repetition of the product name, which the CMS copy almost always opens
 * with — that name is already the title on the line above, so restating it burned ~40 characters
 * of a 160-character budget.
 */
export function productDescription(product: Product, rawProductName: string): string {
  const productName = repairMojibake(rawProductName);
  const explicit = repairMojibake(product.seo?.description || product.seo_description || product.meta_description || product.meta_description_fr);
  if (explicit?.trim()) {
    /*
     * Imported catalogue templates are valid text but weak SERP copy: Omega 3 Fish Oil earned
     * 3,475 impressions at position 7.4 and only 0.75% CTR. Bringing scattered product facts
     * and price into the snippet makes those characters useful. Enrich formulaic identity +
     * shop copy only; hand-written benefit copy remains authoritative.
     */
    // A name-only explicit field can become empty after title removal; it still needs enrichment.
    if (isFormulaicProductDescription(explicit, product, productName)) return enrichDescription(product, productName);
    const plain = buildMetaDescription(explicit, { title: productName, maxLen: 160 });
    if (plain) return plain;
  }
  // Preserve the pre-existing non-template fallback behavior.
  const plain = buildMetaDescription(product.description_fr, { title: productName, maxLen: 90 });
  if (plain) return `${plain} Prix Tunisie. Livraison 24-72h. Protéine Tunisie.`;
  return `Acheter ${productName} en Tunisie – Meilleur prix, livraison rapide, produits authentiques. Sousse, Tunis, toute la Tunisie. Protéine Tunisie.`;
}

/**
 * SHARED WITH THE CRAWLER ROUTE ON PURPOSE.
 *
 * `x-crawler/product/[...slug]` is what middleware rewrites a bot to, and it used to build its
 * own title from `product.seo.title`. So the curated map below — assembled from a Search Console
 * export precisely to raise CTR — was served to browsers and never to Google. Measured on
 * 08/09/2026, the same URL answered differently by user agent:
 *
 *   browser   "Omega 3 Fish Oil WeightWorld 240 capsules – Prix Tunisie"   (the curated one)
 *   Googlebot "Omega 3 fish oil 240 softgel - weightworld – Prix Tunisie"  (the backend's)
 *
 * Both routes now call this, so a title change cannot reach one audience and miss the other.
 */
export function productTitle(product: Product): string {
  /*
   * Search Console opportunity titles (3-month export, 31/08/2026).
   *
   * These are deliberately limited to products with meaningful impressions where the imported
   * catalogue title does not answer the actual query.  They do not invent discounts, stock or
   * delivery promises; price and availability remain in Product/Offer structured data.  Keeping
   * this as a small reviewed map also avoids turning every PDP into the same keyword template.
   */
  const searchOpportunityTitles: Record<string, string> = {
    'omega-3-fish-oil-240-softgel-weightworld':
      'Omega 3 Fish Oil WeightWorld 240 capsules – Prix Tunisie',
    '100-whey-gold-standard-2-27kg':
      'Gold Standard Whey 2,27 kg – Prix Tunisie | Protein.tn',
    'anabolic-whey-80-2-25kg-proactive':
      'Anabolic Whey 80 ProActive 2,25 kg – Prix Tunisie',
    'serious-mass-2-7-kg':
      'Serious Mass 2,7 kg – Prix Tunisie | Optimum Nutrition',
    'serious-mass-5-45-kg-optimum-nutrition':
      'Serious Mass 5,45 kg – Prix Tunisie | Optimum Nutrition',
  };
  const opportunityTitle = product.slug ? searchOpportunityTitles[product.slug] : undefined;
  if (opportunityTitle) return opportunityTitle;

  const explicit = repairMojibake(product.seo?.title || product.seo_title || product.meta_title);
  const name = repairMojibake(product.designation_fr ?? product.slug ?? 'Produit');
  // A title a person wrote in the CMS wins. The backend's own default ("RAW NAME – Prix Tunisie")
  // is boilerplate on top of a shouting catalogue name, and is rewritten like the rest.
  if (explicit?.trim() && !isAutoGeneratedTitle(explicit, name)) return explicit.trim();
  return humanProductTitle(product);
}
