@php
    $details = $commande->details->isNotEmpty() ? $commande->details : $commande->details()->with('product:id,designation_fr')->get();
    $logoUrl = url('/logo.png');
    $adminUrl = url(\App\Filament\Resources\CommandeResource::getUrl('edit', ['record' => $commande]));
    $dateFormatted = $commande->created_at?->locale('fr_FR')->isoFormat('D MMMM YYYY [à] HH:mm');
    $name = trim(($commande->livraison_nom ?? $commande->nom ?? '').' '.($commande->livraison_prenom ?? $commande->prenom ?? ''));
    $phone = $commande->livraison_phone ?? $commande->phone ?? 'Non renseigné';
    $email = $commande->livraison_email ?? $commande->email ?? null;
    $address = collect([$commande->livraison_adresse1 ?? $commande->adresse1 ?? null,$commande->livraison_ville ?? $commande->ville ?? null,$commande->livraison_region ?? $commande->region ?? null,$commande->livraison_code_postale ?? $commande->code_postale ?? null])->filter()->implode(', ');
    $subtotal = (float) ($commande->prix_ht ?? 0);
    $shipping = (float) ($commande->frais_livraison ?? 0);
    $total = (float) ($commande->prix_ttc ?? 0);
    $discount = max(0, $subtotal + $shipping - $total);
    $paymentLabel = ($commande->payment_method ?? '') === 'card' ? 'Carte bancaire' : 'Paiement à la livraison';
    $statusLabel = \App\Models\Commande::getStatusLabel($commande->etat ?? 'nouvelle_commande');
@endphp
<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><title>Nouvelle commande #{{ $commande->numero }}</title>
<style>body,table,td,p,h1,h2{margin:0;padding:0}table{border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0}img{border:0;display:block;height:auto}@media(max-width:620px){.outer{padding:0!important}.shell{width:100%!important;border-radius:0!important}.pad{padding-left:18px!important;padding-right:18px!important}.hero-title{font-size:24px!important}.stat{display:block!important;width:auto!important;border-right:0!important;border-bottom:1px solid #34363c!important;text-align:left!important}.kv-label,.kv-value{display:block!important;width:auto!important;text-align:left!important}.kv-value{padding-top:0!important}.button{display:block!important;text-align:center!important}}</style></head>
<body style="margin:0;background:#f3f4f6;color:#18181b;font-family:Arial,'Helvetica Neue',sans-serif;-webkit-text-size-adjust:100%;"><table role="presentation" width="100%"><tr><td class="outer" align="center" style="padding:28px 12px;"><table role="presentation" width="620" class="shell" style="width:620px;max-width:620px;background:#ffffff;border:1px solid #e5e7eb;border-radius:18px;overflow:hidden;">
<tr><td style="height:6px;background:#df3b05;font-size:0;line-height:0;">&nbsp;</td></tr>
<tr><td class="pad" style="padding:24px 30px;background:#101114;"><img src="{{ $logoUrl }}" width="136" alt="Protein.tn" style="width:136px;max-width:136px;background:#ffffff;border-radius:8px;padding:7px 10px;"><p style="margin-top:20px;font-size:12px;font-weight:bold;letter-spacing:1.3px;text-transform:uppercase;color:#ff6a2a;">Nouvelle commande</p><h1 class="hero-title" style="margin-top:5px;font-size:28px;line-height:1.2;color:#ffffff;">#{{ $commande->numero }}</h1><p style="margin-top:6px;font-size:13px;color:#a1a1aa;">{{ $dateFormatted }}</p></td></tr>
<tr><td style="background:#101114;padding:0 30px 24px;" class="pad"><table role="presentation" width="100%" style="border:1px solid #34363c;border-radius:11px;overflow:hidden;"><tr><td class="stat" width="33%" style="padding:13px 14px;border-right:1px solid #34363c;"><p style="font-size:10px;color:#a1a1aa;">TOTAL</p><p style="margin-top:4px;font-size:18px;font-weight:bold;color:#ff6a2a;">{{ number_format($total,2,'.',' ') }} DT</p></td><td class="stat" width="34%" style="padding:13px 14px;border-right:1px solid #34363c;"><p style="font-size:10px;color:#a1a1aa;">PAIEMENT</p><p style="margin-top:4px;font-size:12px;font-weight:bold;line-height:17px;color:#ffffff;">{{ $paymentLabel }}</p></td><td class="stat" width="33%" style="padding:13px 14px;"><p style="font-size:10px;color:#a1a1aa;">STATUT</p><p style="margin-top:4px;font-size:12px;font-weight:bold;line-height:17px;color:#ffffff;">{{ $statusLabel }}</p></td></tr></table></td></tr>
<tr><td class="pad" style="padding:24px 30px 0;"><h2 style="font-size:13px;letter-spacing:.8px;text-transform:uppercase;">Client et livraison</h2><table role="presentation" width="100%" style="margin-top:11px;border:1px solid #e5e7eb;border-radius:11px;overflow:hidden;">
@foreach([['Nom',$name ?: 'Non renseigné'],['Téléphone',$phone],['Email',$email ?: 'Non renseigné'],['Adresse',$address ?: 'Non renseignée']] as $row)<tr><td class="kv-label" width="30%" style="padding:10px 13px;background:#fafafa;border-bottom:{{ $loop->last ? '0' : '1px solid #eeeeee' }};font-size:12px;font-weight:bold;color:#71717a;">{{ $row[0] }}</td><td class="kv-value" style="padding:10px 13px;border-bottom:{{ $loop->last ? '0' : '1px solid #eeeeee' }};font-size:13px;line-height:19px;color:#18181b;">{{ $row[1] }}</td></tr>@endforeach
@if($commande->note)<tr><td class="kv-label" style="padding:10px 13px;background:#fff7ed;font-size:12px;font-weight:bold;color:#9a3412;">Note</td><td class="kv-value" style="padding:10px 13px;background:#fff7ed;font-size:13px;line-height:19px;color:#7c2d12;">{{ $commande->note }}</td></tr>@endif
</table></td></tr>
<tr><td class="pad" style="padding:22px 30px 0;"><h2 style="font-size:13px;letter-spacing:.8px;text-transform:uppercase;">Produits</h2><table role="presentation" width="100%" style="margin-top:11px;border:1px solid #e5e7eb;border-radius:11px;overflow:hidden;">
@foreach($details as $detail)<tr><td style="padding:12px 13px;border-bottom:{{ $loop->last ? '0' : '1px solid #eeeeee' }};font-size:13px;line-height:19px;">{{ $detail->product->designation_fr ?? 'Produit' }}<br><span style="font-size:12px;color:#71717a;">Quantité : {{ $detail->qte }}</span></td><td align="right" style="padding:12px 13px;border-bottom:{{ $loop->last ? '0' : '1px solid #eeeeee' }};font-size:13px;font-weight:bold;white-space:nowrap;">{{ number_format($detail->qte * $detail->prix_unitaire,2,'.',' ') }} DT</td></tr>@endforeach
</table></td></tr>
<tr><td class="pad" style="padding:12px 30px 22px;"><table role="presentation" width="100%" style="background:#fafafa;border-radius:11px;overflow:hidden;"><tr><td style="padding:11px 13px;font-size:13px;color:#52525b;">Sous-total</td><td align="right" style="padding:11px 13px;font-size:13px;font-weight:bold;">{{ number_format($subtotal,2,'.',' ') }} DT</td></tr>@if($discount > 0)<tr><td style="padding:4px 13px 11px;font-size:13px;color:#16834a;">Remise</td><td align="right" style="padding:4px 13px 11px;font-size:13px;font-weight:bold;color:#16834a;">-{{ number_format($discount,2,'.',' ') }} DT</td></tr>@endif<tr><td style="padding:4px 13px 11px;font-size:13px;color:#52525b;">Livraison</td><td align="right" style="padding:4px 13px 11px;font-size:13px;font-weight:bold;color:{{ $shipping > 0 ? '#18181b' : '#16834a' }};">{{ $shipping > 0 ? number_format($shipping,2,'.',' ').' DT' : 'Gratuite' }}</td></tr><tr><td style="padding:13px;border-top:1px solid #e5e7eb;font-size:16px;font-weight:bold;">Total</td><td align="right" style="padding:13px;border-top:1px solid #e5e7eb;font-size:18px;font-weight:bold;color:#df3b05;">{{ number_format($total,2,'.',' ') }} DT</td></tr></table></td></tr>
<tr><td class="pad" style="padding:0 30px 28px;"><table role="presentation" width="100%"><tr><td align="center" style="background:#df3b05;border-radius:10px;"><a class="button" href="{{ $adminUrl }}" style="display:inline-block;padding:14px 24px;color:#ffffff;text-decoration:none;font-size:14px;font-weight:bold;">Ouvrir et traiter la commande</a></td></tr></table></td></tr>
<tr><td style="padding:18px 30px;background:#f4f4f5;text-align:center;font-size:11px;color:#71717a;">Notification interne Protein.tn</td></tr>
</table></td></tr></table></body></html>
