<?php

namespace App\Console\Commands;

use App\Models\Product;
use App\Services\Catalog\IHerb\IHerbNormalizer;
use App\Services\Seo\ProductSeoDefaults;
use App\Services\Seo\SeoNotifier;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use RuntimeException;

/** Repair only published name collisions backed by distinct iHerb source titles. */
class CatalogIHerbDisambiguateNames extends Command
{
    protected $signature = 'catalog:iherb:disambiguate-names {--apply : Write reviewed names and autogenerated titles}';

    protected $description = 'Preview or repair imported product name collisions without changing URLs';

    public function handle(IHerbNormalizer $normalizer, SeoNotifier $notifier): int
    {
        $apply = (bool) $this->option('apply');
        // Include published non-imported names in each group, so a proposed name cannot silently
        // collide with one. A product with zero or multiple source rows makes its group unsafe.
        $rows = DB::table('products as p')
            ->leftJoin('external_catalog_products as e', function ($join): void {
                $join->on('e.product_id', '=', 'p.id')->where('e.provider', '=', 'iherb');
            })
            ->where('p.publier', 1)
            ->whereNotNull('p.designation_fr')
            ->select('p.id', 'p.slug', 'p.designation_fr', 'p.meta_title', 'p.seo_title',
                'e.source_title', 'e.id as source_id')
            ->orderBy('p.id')->get();

        $groups = [];
        foreach ($rows as $row) {
            $groups[$this->fold((string) $row->designation_fr)][(int) $row->id][] = $row;
        }

        $table = [];
        $groupsFound = $groupsReady = $groupsSkipped = $productsReady = $unresolved = $human = 0;
        foreach ($groups as $members) {
            if (count($members) < 2) {
                continue;
            }
            $groupsFound++;
            $flat = array_map(static fn (array $set) => $set[0], array_values($members));
            $reason = null;
            foreach ($members as $set) {
                if (count($set) !== 1 || trim((string) $set[0]->source_title) === '') {
                    $reason = 'missing or ambiguous iHerb source';
                    break;
                }
            }
            if ($reason !== null) {
                $groupsSkipped++;
                $this->reportSkipped($flat, $reason);
                continue;
            }
            $sourceKeys = array_unique(array_map(fn ($row) => $this->fold($row->source_title), $flat));
            if (count($sourceKeys) < 2) {
                continue;
            }

            $allCandidates = array_map(fn ($row) => $this->candidates($normalizer, $row->source_title), $flat);
            $plans = [];
            foreach ($flat as $index => $row) {
                $qualifier = null;
                foreach ($allCandidates[$index] as $candidate) {
                    if ($this->contains($row->designation_fr, $candidate['label'])) {
                        continue;
                    }
                    $occurrences = 0;
                    foreach ($allCandidates as $other) {
                        if (in_array($candidate['key'], array_column($other, 'key'), true)) {
                            $occurrences++;
                        }
                    }
                    if ($occurrences < count($flat)) {
                        $qualifier = $candidate['label'];
                        break;
                    }
                }
                $newName = $qualifier === null ? $row->designation_fr : $this->insert($row->designation_fr, $qualifier);
                if (mb_strlen($newName) > 500) {
                    $reason = 'proposed name exceeds 500 characters';
                }
                $plans[] = ['row' => $row, 'name' => $newName, 'qualifier' => $qualifier];
            }
            $newKeys = array_map(fn ($plan) => $this->fold($plan['name']), $plans);
            if (count(array_unique($newKeys)) !== count($plans)) {
                $reason = 'resulting names still collide';
            }
            foreach ($newKeys as $key) {
                if (isset($groups[$key]) && $key !== $this->fold($flat[0]->designation_fr)) {
                    $reason = 'proposed name collides with another published product';
                }
            }
            if ($reason !== null) {
                $groupsSkipped++;
                $this->reportSkipped($flat, $reason);
                continue;
            }

            $groupsReady++;
            foreach ($plans as &$plan) {
                $row = $plan['row'];
                $changes = [];
                foreach (['seo_title', 'meta_title'] as $column) {
                    $old = trim((string) $row->$column);
                    if ($plan['name'] === $row->designation_fr || $old === '') {
                        $changes[$column] = $row->$column;
                    } elseif ($this->autoTitle($old, $row->designation_fr)) {
                        $changes[$column] = ProductSeoDefaults::defaultTitle($plan['name']);
                    } else {
                        $changes[$column] = $row->$column;
                        $human++;
                        $this->line("kept, human title: #{$row->id} {$column}: {$old}");
                    }
                }
                $plan['titles'] = $changes;
                if ($plan['qualifier'] === null) {
                    $unresolved++;
                    $this->warn("No qualifier: #{$row->id} {$row->source_title}");
                } else {
                    $productsReady++;
                }
                $table[] = [$row->id, $row->slug, $row->designation_fr, $plan['name'],
                    $row->meta_title, $changes['meta_title'], $row->source_title];
            }
            unset($plan);

            if ($apply) {
                DB::transaction(function () use ($plans): void {
                    foreach ($plans as $plan) {
                        $row = $plan['row'];
                        if ($plan['name'] === $row->designation_fr) {
                            continue;
                        }
                        $update = ['designation_fr' => $plan['name'], 'updated_at' => now()];
                        foreach (['seo_title', 'meta_title'] as $column) {
                            if ($plan['titles'][$column] !== $row->$column) {
                                $update[$column] = $plan['titles'][$column];
                            }
                        }
                        $changed = DB::table('products')->where('id', $row->id)
                            ->where('publier', 1)->where('designation_fr', $row->designation_fr)
                            ->update($update);
                        if ($changed !== 1) {
                            throw new RuntimeException("Product #{$row->id} changed during this run; group rolled back");
                        }
                    }
                });
                // Query-builder updates avoid observers and their unrelated SEO defaults. Invoke
                // the same SeoNotifier hook ProductSeoObserver::saved uses, now that rows committed.
                foreach ($plans as $plan) {
                    if ($plan['name'] !== $plan['row']->designation_fr) {
                        $notifier->productChangedNow(Product::findOrFail($plan['row']->id));
                    }
                }
            }
        }

        $this->table(['id', 'slug', 'old name', 'new name', 'old meta_title', 'new meta_title', 'source_title'], $table);
        $this->info(sprintf('%s: %d collision groups, %d ready, %d skipped; %d names to change, %d without qualifier; %d human titles kept.',
            $apply ? 'Applied' : 'Dry run', $groupsFound, $groupsReady, $groupsSkipped, $productsReady, $unresolved, $human));

        return self::SUCCESS;
    }

    /** @return list<array{key:string,label:string}> */
    private function candidates(IHerbNormalizer $normalizer, string $source): array
    {
        $out = [];
        // Dose first: packSize deliberately ignores per-capsule strengths when a count is present.
        preg_match_all('~(?<![\d,])(\d{1,3}(?:,\d{3})+(?:\.\d+)?|\d+(?:\.\d+)?)\s*(mg|mcg|µg|μg|iu|ui)\b~iu', $source, $doses, PREG_SET_ORDER);
        foreach ($doses as $dose) {
            $unit = in_array(mb_strtolower($dose[2]), ['mcg', 'μg'], true) ? 'µg' : mb_strtolower($dose[2]);
            $unit = in_array($unit, ['iu', 'ui'], true) ? 'UI' : $unit;
            $number = IHerbNormalizer::qualifierNumber((float) str_replace(',', '', $dose[1]));
            $this->add($out, $number.' '.$unit);
        }
        // packSize prefers metric mass over count; recover a count separately when both occur.
        preg_match_all('~(?<![\d,])(?:\d{1,3}(?:,\d{3})+|\d+)\s*(?:veggie capsules|vegetarian capsules|vegan capsules|veg capsules|veggie caps|vegan caps|veg caps|soft gels|softgels|capsules|caps|tablets|tabs|gummies|lozenges|packets|servings)\b~iu', $source, $counts);
        foreach ($counts[0] as $countText) {
            $count = $normalizer->packSize($countText);
            if ($count !== null) {
                $label = IHerbNormalizer::packLabel($count['quantity'], $count['unit']);
                if ($label !== null) {
                    $label = preg_replace('~^\d+(?:,\d+)?~u', IHerbNormalizer::qualifierNumber($count['quantity']), $label) ?? $label;
                    $this->add($out, $label);
                }
            }
        }
        $pack = $normalizer->packSize($source);
        if ($pack !== null) {
            $label = IHerbNormalizer::packLabel($pack['quantity'], $pack['unit']);
            if ($label !== null) {
                $label = preg_replace('~^\d+(?:,\d+)?~u', IHerbNormalizer::qualifierNumber($pack['quantity']), $label) ?? $label;
                $this->add($out, $label);
            }
        }
        $flavour = $normalizer->flavour($source);
        if ($flavour !== null) {
            $this->add($out, $flavour);
        }
        foreach (['Double Strength', 'Extra Strength', 'High Potency', 'Sustained Release', 'Time Release', 'Chewable'] as $descriptor) {
            if (preg_match('~\b'.str_replace(' ', '\s+', $descriptor).'\b~i', $source) === 1) {
                $this->add($out, $descriptor);
            }
        }

        return $out;
    }

    /** @param list<array{key:string,label:string}> $out */
    private function add(array &$out, string $label): void
    {
        $key = $this->fold($label);
        if ($label !== '' && ! in_array($key, array_column($out, 'key'), true)) {
            $out[] = ['key' => $key, 'label' => $label];
        }
    }

    private function insert(string $name, string $qualifier): string
    {
        $parts = explode(' – ', $name);
        array_splice($parts, count($parts) > 1 ? count($parts) - 1 : 1, 0, [$qualifier]);

        return implode(' – ', $parts);
    }

    private function fold(string $text): string
    {
        $ascii = mb_strtolower(Str::ascii($text), 'UTF-8');
        // Treat the French thousands space and iHerb's US thousands comma as the same number.
        $ascii = preg_replace('~(?<=\d)[ ,](?=\d{3}(?:\D|$))~', '', $ascii) ?? $ascii;

        return trim(preg_replace('~[^a-z0-9]+~', ' ', $ascii) ?? $ascii);
    }

    private function contains(string $name, string $label): bool
    {
        return str_contains(' '.$this->fold($name).' ', ' '.$this->fold($label).' ');
    }

    /** Mirrors productMetaDescription.ts:isAutoGeneratedTitle for the old name. */
    private function autoTitle(string $title, string $oldName): bool
    {
        if ($title === ProductSeoDefaults::defaultTitle($oldName)) {
            return true;
        }
        $explicit = $this->fold($title);
        $name = $this->fold($oldName);
        if ($name === '' || ! str_starts_with($explicit, $name)) {
            return false;
        }
        $rest = trim(substr($explicit, strlen($name)));
        if ($rest === '') {
            return true;
        }
        $suffix = ['prix', 'tunisie', 'livraison', 'rapide', 'proteine', 'protein', 'tn', 'et', 'and', 'en', 'ligne', 'pas', 'cher', 'meilleur', 'achat', 'acheter', 'boutique'];
        foreach (explode(' ', $rest) as $word) {
            if (! in_array($word, $suffix, true)) {
                return false;
            }
        }

        return true;
    }

    /** @param list<object> $members */
    private function reportSkipped(array $members, string $reason): void
    {
        $this->warn('Skipped group '.$members[0]->designation_fr.': '.$reason);
        foreach ($members as $row) {
            $this->line("  #{$row->id} {$row->slug} | ".($row->source_title ?? '(no source title)'));
        }
    }
}
