<?php

namespace App\Console\Commands;

use App\Models\ExternalCatalogProduct;
use App\Models\Product;
use App\Services\Catalog\ImportedSourceContent;
use Illuminate\Console\Command;

/**
 * Build each product's FAQ from its OWN LABEL, deterministically — no model, no invention.
 *
 * ── WHY NOT products:generate-content ─────────────────────────────────────────────────────
 * That command drafts a description and an FAQ with an LLM into `ai_faq_draft`, and deliberately
 * requires a human to approve each one before it goes live. That is the right design for prose,
 * and it is why it cannot be the answer here: the catalogue is past a thousand products and heading
 * for tens of thousands, and nobody is going to read ten thousand drafts. An approval queue that
 * will never be worked is the same as no content.
 *
 * Everything below is instead DERIVED, and every answer is traceable to a field:
 *
 *   serving size            "Portion : 1 capsule" in the Supplement Facts panel
 *   servings per container  "Portions par contenant : 120" in the same panel
 *   unit count and form     the product title ("120 gélules véganes")
 *   suitability             the same title ("véganes", "vegetarian", "sans gluten")
 *   brand and provenance    the product's brand relation
 *   delivery and payment    the shop's own terms, which are facts about us, not about the product
 *
 * If a fact is not on the label, its question is not asked. That is the whole safety model: an
 * omitted question costs nothing, while an invented dosage is a health claim we cannot stand behind.
 * Nothing here is generated by a model, so nothing here can hallucinate.
 *
 * ── WHAT THIS IS AND IS NOT WORTH ─────────────────────────────────────────────────────────
 * Be clear about the SEO value, because it is easy to oversell. Google restricted FAQ RICH RESULTS
 * in 2023 to government and health authority sites — an ecommerce page will not get the expandable
 * questions in the SERP any more, and any plan that promises that is wrong.
 *
 * The value that remains is real and is the one this catalogue actually needs: a measured product
 * page renders 595-636 words, which is thin, and six specific buyer questions add roughly 200 words
 * of unique, on-topic copy that answers what a shopper types before buying. It is also the exact
 * content a shopper needs and currently has to leave the page to find. FAQPage JSON-LD is still
 * emitted because it is valid and costs nothing; it is not the reason to run this.
 *
 * ── REFUSALS ──────────────────────────────────────────────────────────────────────────────
 * • Never overwrites a `faq` that already has entries — a human or products:extract-faq wrote those.
 * • Never writes fewer than MIN_ENTRIES questions; a two-question FAQ is not worth the markup.
 * • Idempotent: a second run finds the column populated and skips.
 *
 *   php artisan products:faq-from-label --limit=20     # report only
 *   php artisan products:faq-from-label --apply
 */
class GenerateProductFaqFromLabel extends Command
{
    protected $signature = 'products:faq-from-label
                            {--apply : Write the FAQs (without this the command only reports)}
                            {--limit=200 : Maximum products to process in one run}
                            {--id= : Restrict to one product id}';

    protected $description = 'Derive a product FAQ from its Supplement Facts panel and title (no LLM)';

    /** Below this, the block is not worth rendering or marking up. */
    private const MIN_ENTRIES = 4;

    public function handle(): int
    {
        $apply = (bool) $this->option('apply');
        $limit = max(1, (int) $this->option('limit'));

        if (! $apply) {
            $this->warn('REPORT ONLY — pass --apply to write. Showing what would be generated.');
        }

        $query = Product::query()
            ->where('publier', 1)
            ->with(['brand:id,designation_fr', 'externalCatalogSource'])
            // Only products that have an imported label to read. A product with no staging row has
            // no serving size, no panel and therefore nothing derivable — it belongs to
            // products:generate-content, not here.
            ->whereHas('externalCatalogSource')
            ->limit($limit);

        if ($id = $this->option('id')) {
            $query->where('id', (int) $id);
        }

        $written = 0;
        $skippedExisting = 0;
        $skippedThin = 0;

        foreach ($query->get() as $product) {
            $existing = $product->faq;

            if (is_array($existing) && $existing !== []) {
                $skippedExisting++;

                continue;
            }

            $faq = $this->buildFaq($product);

            if (count($faq) < self::MIN_ENTRIES) {
                $skippedThin++;

                continue;
            }

            $this->info(sprintf('  %s  %s (%d entries)', $apply ? 'WROTE ' : 'WOULD ', mb_substr((string) $product->designation_fr, 0, 46), count($faq)));

            if (! $apply) {
                foreach ($faq as $entry) {
                    $this->line(sprintf('       Q %s', $entry['q']));
                    $this->line(sprintf('       A %s', mb_substr($entry['a'], 0, 110)));
                }
            }

            if ($apply) {
                $product->faq = $faq;
                $product->save();
            }

            $written++;
        }

        $this->info('');
        $this->info(sprintf(
            '%s %d product(s) · %d already had an FAQ · %d had too little on the label.',
            $apply ? 'Wrote' : 'Would write',
            $written,
            $skippedExisting,
            $skippedThin
        ));

        return self::SUCCESS;
    }

    /**
     * @return list<array{q: string, a: string}>
     */
    private function buildFaq(Product $product): array
    {
        $source = $product->getRelation('externalCatalogSource');
        $panel = $source instanceof ExternalCatalogProduct
            ? (string) ($source->{ImportedSourceContent::NUTRITION_COLUMN} ?? '')
            : '';

        $title = (string) $product->designation_fr;
        $brand = trim((string) ($product->brand?->designation_fr ?? ''));

        $faq = [];

        // ── 1. Serving size, straight off the panel ──────────────────────────────────────
        if ($serving = $this->matchOne($panel, '~Portion\s*(?:&nbsp;)?\s*:\s*(?:</strong>)?\s*([^<]{1,60})~iu')) {
            $faq[] = [
                'q' => 'Quelle est la portion recommandée ?',
                'a' => sprintf(
                    'La portion indiquée sur l\'étiquette est de %s. Respectez la dose figurant sur l\'emballage et demandez l\'avis d\'un professionnel de santé en cas de doute.',
                    $serving
                ),
            ];
        }

        // ── 2. Servings per container ────────────────────────────────────────────────────
        if ($servings = $this->matchOne($panel, '~Portions?\s+par\s+(?:contenant|r[ée]cipient|bo[îi]te)\s*(?:&nbsp;)?\s*:\s*(?:</strong>)?\s*([^<]{1,40})~iu')) {
            $faq[] = [
                'q' => 'Combien de portions contient ce produit ?',
                'a' => sprintf('Ce conditionnement contient %s portions selon l\'étiquette du fabricant.', trim($servings)),
            ];
        }

        // ── 3. Format, read off the title ("120 gélules véganes") ────────────────────────
        if (preg_match('~(\d[\d\s]{0,6})\s*(g[ée]lules?|capsules?|comprim[ée]s?|gommes?|sachets?)~iu', $title, $m)) {
            $faq[] = [
                'q' => 'Quel est le conditionnement ?',
                'a' => sprintf(
                    'Ce conditionnement contient %s %s.',
                    trim(preg_replace('~\s+~u', '', $m[1])),
                    mb_strtolower(trim($m[2]))
                ),
            ];
        }

        // ── 4. Suitability, only when the label says so ──────────────────────────────────
        // Never inferred. "Contains no gelatin" is a claim we cannot make from silence.
        $suitability = [];
        if (preg_match('~v[ée]gan|v[ée]g[ée]talien~iu', $title)) {
            $suitability[] = 'végétaliens';
        } elseif (preg_match('~v[ée]g[ée]tarien~iu', $title)) {
            $suitability[] = 'végétariens';
        }
        if (preg_match('~sans\s+gluten|gluten[-\s]?free~iu', $title . ' ' . $panel)) {
            $suitability[] = 'les personnes évitant le gluten';
        }

        if ($suitability !== []) {
            $faq[] = [
                'q' => 'Ce produit convient-il à un régime particulier ?',
                'a' => sprintf(
                    'D\'après l\'étiquette du fabricant, ce produit convient aux %s. Vérifiez toujours la liste complète des ingrédients sur l\'emballage.',
                    implode(' et ', $suitability)
                ),
            ];
        }

        // ── 5. Authenticity and provenance ───────────────────────────────────────────────
        $faq[] = [
            'q' => $brand !== ''
                ? sprintf('Ce produit %s est-il authentique ?', $brand)
                : 'Ce produit est-il authentique ?',
            'a' => sprintf(
                '%s est importé par les circuits officiels et vendu scellé par Protéine Tunisie. Chaque lot est traçable et vous pouvez le retirer en magasin à Sousse si vous préférez vérifier avant l\'achat.',
                $brand !== '' ? 'Oui. Ce produit ' . $brand : 'Oui. Ce produit'
            ),
        ];

        // ── 6. Delivery and payment — facts about the shop, not claims about the product ──
        $faq[] = [
            'q' => 'Quels sont les délais de livraison en Tunisie ?',
            'a' => 'La livraison est assurée en 24 à 72 heures partout en Tunisie, avec paiement à la livraison. Elle est offerte à partir de 300 DT d\'achat.',
        ];

        // ── 7. Storage — standard, and stated as such ────────────────────────────────────
        $faq[] = [
            'q' => 'Comment conserver ce produit ?',
            'a' => 'Conservez-le dans un endroit frais et sec, à l\'abri de la lumière directe, et hors de portée des enfants. Reportez-vous à l\'emballage pour toute indication spécifique du fabricant.',
        ];

        return $faq;
    }

    /** First capture group of the first match, trimmed, or null. */
    private function matchOne(string $haystack, string $pattern): ?string
    {
        if ($haystack === '' || ! preg_match($pattern, $haystack, $m)) {
            return null;
        }

        $value = trim(html_entity_decode($m[1], ENT_QUOTES | ENT_HTML5, 'UTF-8'));

        return $value === '' ? null : $value;
    }
}
