/** @type {() => import('next').Redirect[]} */
function buildRedirects() {
  const p = (source, destination) => ({ source, destination, permanent: true });

  return [
    // ── www → non-www (host-conditional, must stay first) ─────────────────
    {
      source: '/:path*',
      has: [{ type: 'host', value: 'www.protein.tn' }],
      destination: 'https://protein.tn/:path*',
      permanent: true,
    },

    // ── Locale prefix ─────────────────────────────────────────────────────
    p('/en', '/'),
    p('/en/', '/'),

    // ── Legacy alias ──────────────────────────────────────────────────────
    p('/about', '/qui-sommes-nous'),
    p('/xmlrpc.php', '/'),

    // ── Blog ──────────────────────────────────────────────────────────────
    p('/blogs', '/blog'),
    p('/blogs/:path*', '/blog'),
    p('/blog/qu-est-ce-que-la-proteine-whey', '/blog'),
    p('/nutrition-guide', '/blog'),
    p('/programme-dentrainement-musculation', '/blog'),
    p('/programme-dentrainement-musculation/', '/blog'),

    // ── Static info pages ─────────────────────────────────────────────────
    p('/page/:path*', '/qui-sommes-nous'),
    p('/connexion', '/contact'),
    p('/connexion/', '/contact'),
    p('/contact-us', '/contact'),
    p('/contact-us/', '/contact'),

    // ── Products / shop (generic) ─────────────────────────────────────────
    p('/products', '/shop'),
    p('/produit', '/shop'),
    p('/musculation-products', '/shop'),
    p('/musculation-products/:path*', '/shop'),
    p('/produits/:path*', '/shop'),
    p('/collections/:path*', '/shop'),

    // ── Flat product slugs (old URLs without category prefix) ─────────────
    p('/accessoires-rack-jx-fitness', '/musculation/accessoires-rack-jx-fitness'),
    p('/acides-amines', '/bcaa'),
    p('/banc-de-musculation-developpe-incline', '/musculation'),
    p('/banc-reglable-mnd-fitness', '/musculation'),
    p('/bcaa-gluta-500g-scenit-nutrition', '/bcaa'),
    p('/beef-mass-plus-27kg-big-ramy-labs', '/proteine-de-boeuf/beef-mass-plus-27kg-big-ramy-labs'),
    p('/big-ramy-labs-beef-mass-gainer-4-9kg', '/big-ramy-labs'),
    p('/carbo-plus-1kg-universal', '/glucides/carbo-plus-1kg-universal'),
    p('/complements-alimentaires', '/proteines'),
    p('/creatine-300gr-challenger-nutrition', '/creatine/creatine-300gr-challenger-nutrition'),
    p('/deficit-calorique', '/perte-de-poids'),
    p('/eaa-bcaa-390gr-challenger-nutrition', '/bcaa'),
    p('/fat-burner', '/bruleurs-de-graisse'),
    p('/glutamine/', '/glutamine'),
    p('/gold-creatine-kevin-levrone-300-g', '/whey-isolate/gold-iso-2-kg-kevin-levrone'),
    p('/gold-l-carnitine-3000-500ml', '/bruleurs-de-graisse'),
    p('/golds-gym', '/brands'),
    p('/hack-squat-jx-fitness', '/musculation/hack-squat-jx-fitness'),
    p('/hydroxycut-hardcore-elite-100-caps-muscletech', '/bruleurs-de-graisse'),
    p('/isolat-de-whey', '/whey-isolate'),
    p('/king-real-preworkout-500gr-real-pharm-tunisie', '/pre-workout'),
    p('/les-complements-alimentaires', '/proteines'),
    p('/les-complements-alimentaires/', '/proteines'),
    p('/magnesium-bisglycinate-vitamine-b6-1422mg-weightworld', '/magnesium/magnesium-bisglycinate-vitamine-b6-1422mg-weightworld'),
    p('/mass-gainer', '/gainers-proteines'),
    p('/mass-gainer-zero-7kg-eric-favre', '/gainers-proteines'),
    p('/micronised-creatine-317g-tunisie-purete-99-meilleur-prix', '/creatine'),
    p('/omega-3-fish-oil-240-softgel-weightworld', '/omega-3'),
    p('/opti-men-150-tabs-optimum-nutrition', '/vitamines'),
    p('/opti-men-90-tabs-optimum-nutrition', '/vitamines'),
    p('/opti-women-120-caps-optimum-nutrition', '/vitamines/opti-women-120caps'),
    p('/opti-women-60-caps-optimum-nutrition', '/vitamines/opti-women-60caps'),
    p('/pack-gain-musculaire-rapide', '/gainers-proteines/pack-gain-musculaire-rapide'),
    p('/pack-premium-elite', '/whey-hydrolysee/pack-premium-elite'),
    p('/pack-ultimate-muscle', '/proteine-de-boeuf/pack-ultimate-muscle'),
    p('/pre-intra-post-workout', '/pre-workout'),
    p('/pre-intra-post-workout/', '/pre-workout'),
    p('/premium-v-bulk-27kg-victor-martinez', '/gainers-proteines/premium-v-bulk-5-5kg-victor-martinez'),
    p('/protein-vegan-1-5kg-eric-favre', '/proteines'),
    p('/proteine', '/proteines'),
    p('/proteine-de-caseine', '/proteines'),
    p('/proteine-whey', '/whey-isolate'),
    p('/serious-mass-5-45-kg-optimum-nutrition', '/gainers-proteines'),
    p('/serious-mass-5-45kg', '/gainers-proteines'),
    p('/squat-rack-jx-fitness', '/musculation/squat-rack-jx-fitness'),
    p('/support-pour-disques-de-musculation', '/musculation/support-pour-disques-de-musculation'),
    p('/vegan-vitamin-d3-k2-240-tablets-weightworld', '/proteines-vegetales'),
    p('/vitamin-c-1000-mg-90-tabs-gymbeam', '/vitamines'),
    p('/zinc-bisglycinate-400-comprimes-weightworld', '/zinc'),
    p('/zumub-omega-3-90-caps', '/omega-3'),
    // Old blog slug with encoded accent (é = %C3%A9)
    p('/quand-prendre-de-la-cr%C3%A9atine-le-guide-complet-pour-optimiser-vos-resultats-2025', '/blog'),

    // ── /brand/:slug  (specific first → catch-all to /brands) ────────────
    p('/brand/BIOTECH-USA', '/biotech-usa'),
    p('/brand/BPI-SPORTS', '/bpi-sports'),
    p('/brand/CHALLENGER-NUTRITION', '/challenger-nutrition'),
    p('/brand/HX-NUTRITION', '/hx-nutrition'),
    p('/brand/MUSCLETECH', '/muscletech'),
    p('/brand/NUTREX-RESEARCH', '/nutrex-research'),
    p('/brand/OPTIMUM-NUTRITION', '/optimum-nutrition'),
    p('/brand/OSTROVIT', '/ostrovit'),
    p('/brand/REAL-PHARM', '/real-pharm'),
    p('/brand/ULTIMATE-NUTRITION', '/ultimate-nutrition'),
    p('/brand/UNIVERSAL-NUTRITION', '/universal-nutrition'),
    p('/brand/VICTOR-MARTINEZ', '/victor-martinez'),
    p('/brand/WILLIAM-BONAC', '/william-bonac'),
    p('/brand/YAVA-LABS', '/yava-labs'),
    p('/brand/:path*', '/brands'),

    // ── /brands/:slug  (specific first → catch-all to /brands) ───────────
    p('/brands/big-ramy-labs', '/big-ramy-labs'),
    p('/brands/eric-favre', '/eric-favre'),
    p('/brands/hx-nutrition', '/hx-nutrition'),
    p('/brands/jx-fitness', '/jx-fitness'),
    p('/brands/mnd-fitness', '/mnd-fitness'),
    p('/brands/olimp-sport-nutrition', '/olimp-sport-nutrition'),
    p('/brands/ostrovit', '/ostrovit'),
    p('/brands/real-pharm', '/real-pharm'),
    p('/brands/scenit-nutrition', '/scenit-nutrition'),
    p('/brands/scivation', '/scivation'),
    p('/brands/:path*', '/brands'),

    // ── /categorie/:path* ─────────────────────────────────────────────────
    p('/categorie/acides-amines', '/bcaa'),
    p('/categorie/complements-alimentaires', '/proteines'),
    p('/categorie/complements-d-entrainement', '/performance'),
    p('/categorie/equipements-et-accessoires-sportifs', '/shop'),
    p('/categorie/pre-intra-and-post-workout', '/shop'),
    p('/categorie/proteines', '/proteines'),
    p('/categorie/vetements-et-accessoires', '/vetements'),
    p('/categorie/:path*', '/proteines'),

    // ── /categories/:path* ────────────────────────────────────────────────
    p('/categories/complements-d-entrainement', '/performance'),
    p('/categories/equipements-et-accessoires-sportifs', '/shop'),
    p('/categories/:path*', '/shop'),

    // ── /category/:slug  (specific first → catch-all to /shop) ───────────
    p('/category/749-packs', '/packs'),
    p('/category/bandes-de-soutien-musculaire', '/musculation'),
    p('/category/ceinture-de-musculation', '/musculation'),
    p('/category/complements-d-entrainement', '/performance'),
    p('/category/fat-burner', '/bruleurs-de-graisse'),
    p('/category/gainer', '/gainers-proteines'),
    p('/category/gants-de-musculation-et-fitness', '/musculation'),
    p('/category/isolat-de-whey', '/whey-isolate'),
    p('/category/materiel-de-musculation', '/musculation'),
    p('/category/proteine', '/proteines'),
    p('/category/proteine-whey', '/whey-isolate'),
    p('/category/:path*', '/shop'),

    // ── /subcategories/:slug ──────────────────────────────────────────────
    p('/subcategories/acides-amines', '/bcaa'),
    p('/subcategories/boosters-hormonaux', '/boosters-hormonaux'),
    p('/subcategories/bruleurs-de-graisse', '/bruleurs-de-graisse'),
    p('/subcategories/ceinture-de-musculation', '/musculation'),
    p('/subcategories/equipement-cardio-fitness', '/cardio-fitness'),
    p('/subcategories/fat-burner', '/bruleurs-de-graisse'),
    p('/subcategories/materiel-de-musculation', '/musculation'),
    p('/subcategories/proteine-whey', '/whey-isolate'),
    p('/subcategories/recuperation-apres-entrainement', '/shop'),
    p('/subcategories/:path*', '/shop'),

    // ── /product-category/  (WordPress legacy) ────────────────────────────
    p('/product-category/acides-amines/stimulants-hormonaux', '/shop'),
    p('/product-category/acides-amines/stimulants-hormonaux/', '/shop'),
    p('/product-category/acides-amines/vitamines', '/vitamines'),
    p('/product-category/acides-amines/vitamines/', '/vitamines'),
    p('/product-category/perte-de-poids/fat-burner', '/bruleurs-de-graisse'),
    p('/product-category/perte-de-poids/fat-burner/', '/bruleurs-de-graisse'),
    p('/product-category/perte-de-poids/l-carnitine', '/bruleurs-de-graisse'),
    p('/product-category/perte-de-poids/l-carnitine/', '/bruleurs-de-graisse'),
    p('/product-category/prise-de-masse/mass-gainer', '/gainers-proteines'),
    p('/product-category/prise-de-masse/mass-gainer/', '/gainers-proteines'),
    p('/product-category/proteines/proteine-de-boeuf', '/proteine-de-boeuf'),
    p('/product-category/proteines/proteine-de-boeuf/', '/proteine-de-boeuf'),
    p('/product-category/proteines/whey-isolate', '/whey-isolate'),
    p('/product-category/proteines/whey-isolate/', '/whey-isolate'),
    p('/product-category/:path*', '/shop'),

    // ── /shop/:path  specific broken sub-paths (no catch-all — /shop is valid) ──
    p('/shop/aakg-plus-120caps', '/shop'),
    p('/shop/boogieman-300-g-trec-nutrition', '/shop'),
    p('/shop/bulk-muscle-xl-68-kg', '/shop'),
    p('/shop/bulk-muscle-xl-68-kg/', '/shop'),
    p('/shop/cell-tech-creactor-120-servings-muscletech', '/shop'),
    p('/shop/citruargin-300-g', '/citrulline/citruargin-300-g-real-pharm'),
    p('/shop/citruargin-300-g/', '/citrulline/citruargin-300-g-real-pharm'),
    p('/shop/complements-alimentaires/acides-amines', '/bcaa'),
    p('/shop/complements-d-entrainement/pendant-l-entrainement', '/shop'),
    p('/shop/complements-d-entrainement/recuperation-apres-entrainement', '/shop'),
    p('/shop/crea-core-250g-procell', '/shop'),
    p('/shop/equipements-et-accessoires-sportifs/bandes-de-soutien-musculaire', '/musculation'),
    p('/shop/equipements-et-accessoires-sportifs/ceinture-de-musculation', '/musculation'),
    p('/shop/equipements-et-accessoires-sportifs/equipement-cardio-fitness', '/cardio-fitness'),
    p('/shop/equipements-et-accessoires-sportifs/gants-de-musculation-et-fitness', '/musculation'),
    p('/shop/equipements-et-accessoires-sportifs/materiel-de-musculation', '/musculation'),
    p('/shop/fish-oil-100-softgels', '/shop'),
    p('/shop/fish-oil-100-softgels/', '/shop'),
    p('/shop/hard', '/shop'),
    p('/shop/mutant-amino-300-tab-mutant', '/shop'),
    p('/shop/mutant-amino-300-tab-mutant/', '/shop'),
    p('/shop/pack-3', '/shop'),
    p('/shop/pack-3/', '/shop'),
    p('/shop/pack-4', '/shop'),
    p('/shop/pack-4/', '/shop'),
    p('/shop/perte-de-poids/fat-burner', '/bruleurs-de-graisse'),
    p('/shop/platinum-fish-oil-100-caps', '/shop'),
    p('/shop/platinum-fish-oil-100-caps/', '/shop'),
    p('/shop/proteines/isolat-de-whey', '/whey-isolate'),
    p('/shop/proteines/proteine-whey', '/whey-isolate'),
    p('/shop/proteines/whey-isolate/iso-100-2-3-kg-dymatize', '/shop'),
    p('/shop/proteines/whey-isolate/iso-100-2-3-kg-dymatize/', '/shop'),
    p('/shop/the-shadow-270g', '/shop'),
    p('/shop/the-shadow-270g/', '/shop'),
    p('/shop/xtend-bcaa-420g', '/bcaa/xtend-bcaa-420g'),
    p('/shop/xtend-bcaa-420g/', '/bcaa/xtend-bcaa-420g'),
    p('/shop/zma-pro-90-caps', '/zma/zma-pro-90-caps'),
    p('/shop/zma-pro-90-caps/', '/zma/zma-pro-90-caps'),
  ];
}

module.exports = buildRedirects;
