<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * A structured home for the Supplement Facts panel.
 *
 * ── WHY A SECOND COLUMN ───────────────────────────────────────────────────────────────────
 * `nutrition_values` holds rendered HTML. That is what the page needs and the worst possible thing
 * to store facts in: you cannot query "which products contain creatine", cannot emit schema from it,
 * cannot re-render it in another language or layout, and cannot diff it against a supplier update
 * without parsing your own markup back.
 *
 * So the transcribed rows live here as JSON and `nutrition_values` becomes DERIVED — regenerated by
 * NutritionPanelBuilder whenever this changes. Anything typed straight into nutrition_values still
 * works exactly as before; this column simply takes over when it is present.
 *
 * ── WHY IT MATTERS MORE THAN IT LOOKS ─────────────────────────────────────────────────────
 * Measured on 2026-08-07: the NIH label database matched 0 of the 12 barcoded products (it
 * transcribes US labels; this catalogue is Polish, Spanish and Portuguese), Open Food Facts knew 2,
 * and only 3% of live product pages carry any nutrition content at all. There is no external source
 * that covers this catalogue.
 *
 * What does cover it is the tub itself. Someone is already handling all 309 to scan barcodes. This
 * column is what makes that trip produce structured, re-renderable, schema-ready data instead of a
 * paragraph of HTML — and the label photograph beside it is the evidence anyone can check it
 * against.
 */
return new class extends Migration
{
    public function up(): void
    {
        if (! Schema::hasTable('products') || Schema::hasColumn('products', 'nutrition_facts')) {
            return;
        }

        Schema::table('products', function (Blueprint $table): void {
            // Nullable with no default: "nobody has transcribed this yet" is a real and very common
            // state, and it must not be confused with "this product has no nutrition information".
            $table->json('nutrition_facts')->nullable()->after('nutrition_values');
        });
    }

    public function down(): void
    {
        if (Schema::hasTable('products') && Schema::hasColumn('products', 'nutrition_facts')) {
            Schema::table('products', function (Blueprint $table): void {
                $table->dropColumn('nutrition_facts');
            });
        }
    }
};
