<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Where every externally-sourced product fact came from.
 *
 * ── WHY A SEPARATE TABLE AND NOT MORE COLUMNS ON `products` ───────────────────────────────
 * A column can hold a value. It cannot answer "who said so, when, under what licence, and what did
 * the other source say?" — and those are the questions that decide whether a Supplement Facts panel
 * may be published on a page people dose themselves from.
 *
 * Three things become possible only with this table:
 *
 * 1. CONFLICT WITHOUT AVERAGING. Two sources disagreeing about protein per serving is normal
 *    (different market, different formula revision). Averaging them invents a third number that is
 *    on no label anywhere. Keeping both observations and selecting a winner by source authority is
 *    the only honest resolution, and it needs somewhere to keep the loser.
 *
 * 2. TAKEDOWN. If a rights holder asks us to remove data, "find every field derived from source X"
 *    has to be a query. Without provenance it is an archaeology project.
 *
 * 3. STALENESS. A label record from 2014 for a product that has since been reformulated is worse
 *    than no record. retrieved_at and source_published_at make that visible instead of silent.
 *
 * ── WHAT DOES NOT GO IN HERE ──────────────────────────────────────────────────────────────
 * Nothing generated by a model. An LLM is never a source of fact — it may rephrase an observation
 * recorded here, but its output does not come back in as evidence. Review text and customer
 * identifiers stay out too: this table is about products, not people.
 */
return new class extends Migration
{
    public function up(): void
    {
        if (Schema::hasTable('product_source_observations')) {
            return;
        }

        Schema::create('product_source_observations', function (Blueprint $table) {
            $table->id();

            // No FK constraint: `products` is a legacy table inherited from the deleted application
            // and is not in version control, so its engine and key types cannot be assumed here.
            $table->unsignedBigInteger('product_id')->index();

            // Dotted path into the canonical record, e.g. "nutrition.protein_per_serving",
            // "identity.gtin", "content_facts.ingredients". Kept as a string rather than an enum so
            // a new source can record a new field without a migration.
            $table->string('field_path', 120);

            $table->json('normalized_value')->nullable();
            $table->json('raw_value')->nullable();

            $table->string('source_id', 60);            // 'dsld', 'open_food_facts', 'usda_fdc', …
            $table->string('source_record_id', 120)->nullable();
            $table->text('source_url')->nullable();
            $table->string('source_type', 40);          // 'government', 'open_database', 'manufacturer', …

            $table->timestamp('retrieved_at');
            $table->date('source_published_at')->nullable();

            // sha256 of the payload this observation was read from. Re-fetching an unchanged record
            // must not create a second observation, and a changed hash is the signal to re-review.
            $table->string('content_hash', 64)->index();

            $table->string('license_id', 60)->nullable();       // 'ODbL-1.0', 'CC0-1.0', 'US-Gov-PD'
            $table->string('attribution', 255)->nullable();     // rendered next to the data when the licence requires it

            // How confidently this observation belongs to THIS product. A GTIN match is near
            // certain; a brand+name match is a guess that a human has to confirm, because
            // "Gold Standard Whey" exists in US and EU formulations with different panels.
            $table->decimal('confidence', 4, 3)->default(0);
            $table->string('match_method', 40);                 // 'gtin', 'brand_name', 'manual'

            $table->string('extraction_method', 40)->nullable(); // 'api', 'label_ocr', 'pdf'
            $table->string('extractor_version', 20)->nullable();

            // pending -> a human has not looked at it. Nothing reaches a page from `pending`.
            $table->string('status', 20)->default('pending')->index();
            $table->string('reviewed_by', 120)->nullable();
            $table->timestamp('reviewed_at')->nullable();
            $table->text('review_note')->nullable();

            $table->timestamps();

            // The natural key: one observation per product/field/source/payload. Re-running a
            // connector against unchanged upstream data is then a no-op rather than a duplicate.
            $table->unique(
                ['product_id', 'field_path', 'source_id', 'content_hash'],
                'pso_product_field_source_hash_unique'
            );

            $table->index(['product_id', 'field_path'], 'pso_product_field_index');
            $table->index(['source_id', 'retrieved_at'], 'pso_source_retrieved_index');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('product_source_observations');
    }
};
