import { Metadata } from 'next';
import { htmlToText } from '@/util/sanitizeProductHtml';
import { notFound, permanentRedirect, unstable_rethrow } from 'next/navigation';
import { getErrorStatus } from '@/util/errorStatus';
import { getCategories } from '@/services/api';
// Request-scoped cache: generateMetadata and the page body below both need this category, and
// two separate calls could fail independently (metadata 429 + body OK = 200, generic title,
// no canonical — the exact shell measured under crawl load).
import { getCachedCategoryOrSubCategory as fetchCategoryOrSubCategory } from '@/services/getCachedProductDetails';
import { resolveCanonicalUrl } from '@/util/canonical';
import {
  buildBreadcrumbListSchema,
  buildCollectionPageSchema,
  buildItemListSchema,
  buildProductSchema,
  buildFAQPageSchemaFromQA,
  validateStructuredData,
} from '@/util/structuredData';
import { getCategorySeoContent } from '@/util/categorySeoContent';
import { mergeCategorySeo, type CategorySeoFromApi, type MergedCategorySeo } from '@/util/resolveCategorySeo';
import { getTunisiaKeywordsForCategory, generateTunisiaMetaTitle, generateTunisiaMetaDescription, generateTunisiaH1 } from '@/util/tunisiaCategoryKeywords';
import { getProductLink, getProductPrimarySubCategory } from '@/util/productUrl';
import { generateCategoryIntroFallback } from '@/util/categoryIntroFallback';
import { getEffectivePrice } from '@/util/productPrice';
import { CategorySeoLanding } from '@/app/(shop)/category/CategorySeoLanding';
import { ShopPageClient } from '@/app/(shop)/shop/ShopPageClient';
import { ProductsSkeleton } from '@/app/components/ProductsSkeleton';
import { Suspense } from 'react';
import type { Category, SubCategory } from '@/types';

export type PageProps = {
  params: Promise<{ slug: string }>;
};

// ISR (see app/[slug]/page.tsx): cacheable category HTML for better Core Web Vitals.
export const revalidate = 600;

/** Legacy/wrong slugs → canonical slug (from API). Ensures correct API response and SEO. */
const slugAliases: Record<string, string> = {
  'bandages-de-soutien-musculaire': 'bandes-de-soutien-musculaire',
};

/**
 * Canonical form of a listing slug: alias-resolved and LOWERCASED.
 *
 * URLs are case-sensitive to a crawler, and nothing here normalised case — so /whey-proteine,
 * /Whey-Proteine and /WHEY-PROTEINE all returned 200 with byte-identical content and, worse, each
 * declared ITSELF as canonical. That is three indexable duplicates of every listing and CMS page,
 * generated by any miscapitalised inbound link. Verified live before this change:
 *   /whey-proteine  -> canonical https://protein.tn/whey-proteine
 *   /Whey-Proteine  -> canonical https://protein.tn/Whey-Proteine
 *   /WHEY-PROTEINE  -> canonical https://protein.tn/WHEY-PROTEINE
 *
 * Lowercasing the canonical collapses every case variant onto one URL without needing a redirect,
 * and it is safe here because slug lookups already resolve case-insensitively — /intra-workout and
 * /Intra-Workout both return 200 with the same H1, even though the stored slug is "Intra-Workout".
 * That stored capitalisation is also why one uppercase URL was shipping in the sitemap; the
 * sitemap now emits the lowercase form too.
 */
function getCanonicalSlug(slug: string): string {
  const aliased = slugAliases[slug] ?? slug;
  return aliased.toLowerCase();
}

/** Resolve category/subcategory slugs to links (name + url). */
function resolveRelatedCategories(
  slugs: string[],
  categories: Category[]
): Array<{ slug: string; name: string; url: string }> {
  const out: Array<{ slug: string; name: string; url: string }> = [];
  for (const s of slugs.slice(0, 6)) {
    const cat = categories.find((c) => c.slug === s);
    if (cat) {
      out.push({ slug: cat.slug, name: cat.designation_fr, url: `/${cat.slug}` });
      continue;
    }
    for (const c of categories) {
      const sub = (c.sous_categories || []).find((sc: SubCategory) => sc.slug === s);
      if (sub) {
        out.push({ slug: sub.slug, name: sub.designation_fr, url: `/${sub.slug}` });
        break;
      }
    }
  }
  return out;
}

/** Resolve product slugs to links from a product list. */
function resolveBestProducts(
  slugs: string[],
  products: Array<{ slug?: string; designation_fr?: string; sous_categorie?: { slug?: string }; sous_categories?: Array<{ slug?: string }> }>
): Array<{ slug: string; name: string; url: string }> {
  const bySlug = new Map(products.map((p) => [p.slug ?? '', p]));
  return slugs.slice(0, 6).reduce<Array<{ slug: string; name: string; url: string }>>((acc, s) => {
    const p = bySlug.get(s);
    if (p) {
      // Use new SEO-friendly URL format if subcategory exists
      const subCategory = p.sous_categories?.[0] || p.sous_categorie;
      const url = subCategory?.slug ? `/${subCategory.slug}/${s}` : null;
      acc.push({ slug: s, name: p.designation_fr ?? s, url: url || `/${s}` });
    }
    return acc;
  }, []);
}

/**
 * Derive REAL intro-fallback inputs (product count, most common brands, min price) from the
 * product list already available to the page. Used only to fill an empty intro — never fabricated.
 */
function deriveIntroDataFromProducts(
  products: Array<{ brand?: { designation_fr?: string }; prix?: number; promo?: number; promo_expiration_date?: string }>
): { productCount: number; topBrands: string[]; priceMin: number | null } {
  const list = Array.isArray(products) ? products : [];
  const brandFreq = new Map<string, number>();
  let priceMin: number | null = null;
  for (const p of list) {
    const bname = p.brand?.designation_fr?.trim();
    if (bname) brandFreq.set(bname, (brandFreq.get(bname) || 0) + 1);
    const price = getEffectivePrice(p as any);
    if (typeof price === 'number' && price > 0) {
      priceMin = priceMin === null ? price : Math.min(priceMin, price);
    }
  }
  const topBrands = [...brandFreq.entries()]
    .sort((a, b) => b[1] - a[1])
    .map(([n]) => n)
    .slice(0, 3);
  return { productCount: list.length, topBrands, priceMin };
}

/** CTR-optimized meta title: 55–65 chars, keyword + Tunisia + brand. */
const META_TITLE_MAX_LEN = 65;

function toMetaTitle(seoH1: string | undefined, fallbackName: string | undefined, slug?: string): string {
  if (seoH1?.trim()) {
    const trimmed = seoH1.trim();
    if (trimmed.length <= META_TITLE_MAX_LEN) return trimmed;
    const cut = trimmed.slice(0, META_TITLE_MAX_LEN - 1);
    const lastSpace = cut.lastIndexOf(' ');
    return lastSpace > 40 ? cut.slice(0, lastSpace) : cut;
  }
  if (fallbackName && slug) {
    const tunisiaKeywords = getTunisiaKeywordsForCategory(slug);
    if (tunisiaKeywords) {
      return generateTunisiaMetaTitle(fallbackName, tunisiaKeywords);
    }
    return `${fallbackName} | Protéine Tunisie`;
  }
  return fallbackName ? `${fallbackName} | Proteine Tunisie` : 'Catégorie | Proteine Tunisie';
}

function metaKeywordsList(merged: MergedCategorySeo): string[] | undefined {
  const raw = merged.metaKeywords?.trim();
  if (!raw) return undefined;
  const parts = raw.split(/[,;]/).map((s) => s.trim()).filter(Boolean);
  return parts.length ? [...new Set(parts)] : undefined;
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const canonicalSlug = getCanonicalSlug(slug?.trim() ?? '');
  try {
    const { type, data } = await fetchCategoryOrSubCategory(canonicalSlug);
    const apiTitle =
      type === 'subcategory'
        ? (data as any).sous_category?.designation_fr
        : (data as any).category?.designation_fr;
    const apiSeo = (data as any).seo as CategorySeoFromApi | undefined;
    const seoJson = await getCategorySeoContent(canonicalSlug);
    const merged = mergeCategorySeo(seoJson, apiSeo);
    let metaTitle =
      merged.metaTitle && merged.metaTitle.length <= META_TITLE_MAX_LEN
        ? merged.metaTitle
        : toMetaTitle(merged.h1, apiTitle, canonicalSlug);
    // Ensure brand suffix — API-sourced titles may omit it
    // Skip when title already includes the domain brand (Protein.tn) to avoid double suffix
    const brand = ' | Protéine Tunisie';
    const hasBrand =
      /protéine|proteine|protein\.tn/i.test(metaTitle);
    if (!hasBrand) {
      // Trim the BASE title on a word boundary BEFORE appending the full brand suffix,
      // so the brand (and "Tunisie") is never chopped mid-word. Previously
      // `(metaTitle + brand).slice(0, MAX)` could mangle the suffix to "…Protéine Tuni".
      const maxBase = META_TITLE_MAX_LEN - brand.length;
      if (metaTitle.length > maxBase) {
        const cut = metaTitle.slice(0, maxBase);
        const lastSpace = cut.lastIndexOf(' ');
        metaTitle = (lastSpace > 30 ? cut.slice(0, lastSpace) : cut).trim();
      }
      metaTitle = metaTitle + brand;
    } else if (metaTitle.length > META_TITLE_MAX_LEN) {
      const cut = metaTitle.slice(0, META_TITLE_MAX_LEN - 1);
      const lastSpace = cut.lastIndexOf(' ');
      metaTitle = lastSpace > 40 ? cut.slice(0, lastSpace) : cut;
    }
    const tunisiaKeywords = getTunisiaKeywordsForCategory(canonicalSlug);
    // A CMS description only wins if it is long enough to BE a description.
    //
    // This checked the maximum (<= 500) and nothing else, so "Whey protein tunisie" — 20
    // characters, the entire meta description on /whey-proteine — beat the generated fallback and
    // shipped as the page's snippet. Google gives roughly 155 characters of SERP real estate;
    // spending 20 of them on a repeat of the title throws away the one piece of copy that decides
    // whether a searcher clicks. Several sibling categories had the same stub.
    //
    // 70 is deliberately forgiving: it rejects title-echo stubs while leaving any genuinely
    // written short description intact. Below it, fall through to the category intro, then to the
    // Tunisia-specific generator — both of which say something a buyer can act on.
    const CMS_DESCRIPTION_MIN_LEN = 70;
    const cmsDescription = merged.metaDescription?.trim() ?? '';
    const description =
      cmsDescription.length >= CMS_DESCRIPTION_MIN_LEN && cmsDescription.length <= 500
        ? cmsDescription
        : // htmlToText, not a hand-rolled tag strip: the intro is CMS HTML, so "&amp;" has to be
          // DECODED here. Stripping tags alone left the entity in the text, which then got escaped
          // again on its way into the attribute and reached Google as a literal "&amp;amp;".
          (htmlToText(merged.intro, 160) ||
            generateTunisiaMetaDescription(apiTitle || canonicalSlug, tunisiaKeywords));
    // merged.canonicalUrl is sous_categories.canonical_url / categs.canonical_url — free text.
    // forceProteinDomain only normalised the HOST, so it accepted '/musculation' verbatim even
    // though the admin redirect table 301s /musculation straight back to this page. The guard
    // catches that and falls back to the (always-live) self canonical.
    const canonicalUrl = await resolveCanonicalUrl(merged.canonicalUrl, `/${encodeURIComponent(canonicalSlug)}`);
    const descTrimmed = description.slice(0, 155);
    const ogImageRaw = merged.ogImage || undefined;
    const ogImage = ogImageRaw && /^https?:\/\//i.test(ogImageRaw) && !/\s/.test(ogImageRaw) ? ogImageRaw : undefined;
    const ogAlt = (apiSeo?.og?.image_alt as string | undefined)?.trim() || merged.h1 || apiTitle || 'Catégorie';
    const ogTitleMeta = (merged.ogTitle ?? '').trim() || metaTitle;
    const ogDescMeta = (merged.ogDescription ?? '').trim() || descTrimmed;
    const twitterTitleMeta = (merged.twitterTitle ?? '').trim() || ogTitleMeta;
    const twitterDescMeta = (merged.twitterDescription ?? '').trim() || ogDescMeta;
    const twitterImgRaw = (merged.twitterImage ?? '').trim() || ogImageRaw;
    const twitterImg = twitterImgRaw && /^https?:\/\//i.test(twitterImgRaw) && !/\s/.test(twitterImgRaw) ? twitterImgRaw : undefined;
    const kw = metaKeywordsList(merged);
    const fallbackKeywords = tunisiaKeywords ? [tunisiaKeywords.primary, ...tunisiaKeywords.variations] : [];
    const allKeywords = kw ? [...kw, ...fallbackKeywords] : (fallbackKeywords.length > 0 ? fallbackKeywords : undefined);
    return {
      title: { absolute: metaTitle },
      description: descTrimmed,
      ...(allKeywords ? { keywords: allKeywords } : {}),
      alternates: { canonical: canonicalUrl },
      // Always index resolved categories — never trust admin noindex for live categories
      robots: { index: true, follow: true },
      openGraph: {
        title: ogTitleMeta,
        description: ogDescMeta.slice(0, 200),
        url: canonicalUrl,
        ...(ogImage && { images: [{ url: ogImage, width: 1200, height: 630, alt: ogAlt }] }),
      },
      twitter: {
        card: 'summary_large_image',
        title: twitterTitleMeta,
        description: twitterDescMeta.slice(0, 200),
        ...(twitterImg && { images: [twitterImg] }),
      },
    };
  } catch (e) {
    unstable_rethrow(e);
    // Genuine 404: the page body's own resolution calls notFound() and Next serves a real 404.
    // Describe it as noindex so the interim shell can never be indexed on the way there.
    if (getErrorStatus(e) === 404) {
      return {
        title: 'Catégorie introuvable | Proteine Tunisie',
        robots: { index: false, follow: false },
      };
    }
    // TRANSIENT (429 from the shared per-IP bucket, 5xx, timeout). This catch is THE
    // degraded-render bug: /{slug} AND /x-crawler/category/{slug} both delegate their metadata
    // here, so one throttled call emitted HTTP 200 with the generic title
    // "Catégorie | Proteine Tunisie" and NO canonical, while the page body — a SEPARATE API
    // call — rendered the real product grid. Googlebot indexed a duplicate, canonical-less page.
    // Rethrow instead: Next answers with a 5xx it never caches and the crawler simply retries.
    throw e;
  }
}

export default async function CategoryPage({ params }: PageProps) {
  const { slug } = await params;
  const cleanSlug = slug?.trim();
  if (!cleanSlug) notFound();

  const canonicalSlug = getCanonicalSlug(cleanSlug);
  if (canonicalSlug !== cleanSlug) {
    if (process.env.NODE_ENV === 'development') {
      console.warn(`[category] Slug alias: "${cleanSlug}" → "${canonicalSlug}"`);
    }
    permanentRedirect(`/${encodeURIComponent(canonicalSlug)}`);
  }

  // Start both independent fetches concurrently (was a sequential waterfall: getCategories was fully
  // awaited before the category fetch even began). categories feeds only later related-links /
  // breadcrumbs; the category fetch depends only on the slug. Awaiting the category promise inside
  // the existing try preserves the notFound()/rethrow error handling.
  const categoriesPromise = getCategories().catch((e) => {
    console.error('Error fetching categories:', e);
    return [] as Awaited<ReturnType<typeof getCategories>>;
  });
  const categoryPromise = fetchCategoryOrSubCategory(canonicalSlug);
  const categories = await categoriesPromise;

  try {
    const { type, data } = await categoryPromise;

    if (type === 'subcategory') {
      const sub = data as {
        sous_category: any;
        products: any[];
        brands: any[];
        sous_categories: any[];
        pagination?: any;
      };
      const productsData = {
        products: sub.products ?? [],
        brands: sub.brands ?? [],
        categories: [],
      };
      const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'https://protein.tn';
      const parentCat = sub.sous_category?.categorie;
      const seoJson = await getCategorySeoContent(canonicalSlug);
      const apiSeoSub = (sub as { seo?: CategorySeoFromApi }).seo;
      const merged = mergeCategorySeo(seoJson, apiSeoSub);
      const subCrumbName =
        merged.breadcrumbLabel ||
        merged.h1?.trim() ||
        sub.sous_category?.designation_fr ||
        canonicalSlug;
      const breadcrumbItems = [
        { name: 'Accueil', url: '/' },
        ...(parentCat?.slug
          ? [
              { name: parentCat.designation_fr || parentCat.slug, url: `/${parentCat.slug}` },
              { name: subCrumbName, url: `/${canonicalSlug}` },
            ]
          : [{ name: subCrumbName, url: `/${canonicalSlug}` }]),
      ];
      const breadcrumbSchema = buildBreadcrumbListSchema(breadcrumbItems, baseUrl);
      validateStructuredData(breadcrumbSchema, 'BreadcrumbList');
      const pageTitle = merged.h1?.trim() || sub.sous_category?.designation_fr || canonicalSlug;
      const collectionDesc =
        (merged.metaDescription ||
          merged.intro?.replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim() ||
          '')
          .slice(0, 500)
          .trim() || undefined;
      const collectionPageSchema = buildCollectionPageSchema(pageTitle, `/${canonicalSlug}`, baseUrl, {
        description: collectionDesc,
      });
      validateStructuredData(collectionPageSchema, 'CollectionPage');
      const productList = (sub.products ?? []).slice(0, 20)
        // Use the canonical product URL so ItemList entries match each Product schema's offers.url.
        .map((p: any) => ({ name: p.designation_fr || p.slug, url: getProductLink(p) }))
        .filter((p: { name: string; url: string }) => p.url && p.url !== '/shop/');
      const itemListSchema = productList.length > 0 ? buildItemListSchema(productList, baseUrl, { name: pageTitle }) : null;
      const productSchemas = (sub.products ?? [])
        .slice(0, 6)
        .map((p: any) => buildProductSchema(p, baseUrl))
        .filter(Boolean) as object[];

      const title = merged.h1?.trim() || sub.sous_category?.designation_fr || canonicalSlug;
      // Related-links fallback: uncurated subcategory pages get no relatedCategorySlugs, leaving them
      // with no lateral internal links. Fall back to sibling subcategories under the same parent +
      // the parent category itself so every subcategory is reachable/reaches out.
      const relatedSlugsSub = (merged.relatedCategorySlugs?.length
        ? merged.relatedCategorySlugs
        : (() => {
            const parentSlug = sub.sous_category?.categorie?.slug as string | undefined;
            const parent = parentSlug ? categories.find((c) => c.slug === parentSlug) : undefined;
            const siblingSlugs = (parent?.sous_categories ?? [])
              .map((s: SubCategory) => s.slug)
              .filter((s: string): s is string => Boolean(s) && s !== canonicalSlug);
            return (parentSlug ? [...siblingSlugs, parentSlug] : siblingSlugs).slice(0, 6);
          })()) as string[];
      const relatedCategories = resolveRelatedCategories(relatedSlugsSub, categories);
      // Unique intro fallback (thin-content): when there is no admin/content-file intro, synthesize a
      // distinct paragraph from this page's real product data so every indexed subcategory has copy.
      const introDataSub = deriveIntroDataFromProducts(sub.products ?? []);
      const introForLandingSub = merged.intro?.trim()
        ? merged.intro
        : generateCategoryIntroFallback({
            name: title,
            productCount: introDataSub.productCount,
            topBrands: introDataSub.topBrands,
            priceMin: introDataSub.priceMin,
          });
      const bestProducts = resolveBestProducts(
        merged.bestProductSlugs?.length ? merged.bestProductSlugs : (productsData.products as any[]).slice(0, 6).map((p: any) => p.slug).filter(Boolean),
        productsData.products as any[]
      );
      const faqPageSchema = merged.faqs?.length ? buildFAQPageSchemaFromQA(merged.faqs) : null;
      if (faqPageSchema) validateStructuredData(faqPageSchema, 'FAQPage');
      const categorySeoLanding = (
        <CategorySeoLanding
          title={title}
          banners={merged.banners}
          intro={introForLandingSub}
          longBottomHtml={null}
          howToChooseTitle={merged.howToChooseTitle?.trim() ? merged.howToChooseTitle : null}
          howToChooseBody={merged.howToChooseBody?.trim() ? merged.howToChooseBody : null}
          faqs={merged.faqs ?? []}
          relatedCategories={relatedCategories}
          bestProducts={bestProducts}
          withFaqSchema={false}
          section="header"
        />
      );
      const hasHowTo = Boolean(merged.howToChooseTitle?.trim() && merged.howToChooseBody?.trim());
      const hasLongBottom = Boolean((merged.longBottomHtml ?? '').trim().length > 0);
      const hasSeoContentBelow =
        (introForLandingSub ?? '').trim().length > 0 ||
        (merged.faqs?.length ?? 0) > 0 ||
        hasHowTo ||
        hasLongBottom ||
        relatedCategories.length > 0 ||
        bestProducts.length > 0;
      const categorySeoLandingBottom = hasSeoContentBelow ? (
        <CategorySeoLanding
          title={title}
          intro={introForLandingSub}
          longBottomHtml={merged.longBottomHtml?.trim() ? merged.longBottomHtml : null}
          howToChooseTitle={merged.howToChooseTitle?.trim() ? merged.howToChooseTitle : null}
          howToChooseBody={merged.howToChooseBody?.trim() ? merged.howToChooseBody : null}
          faqs={merged.faqs ?? []}
          relatedCategories={relatedCategories}
          bestProducts={bestProducts}
          withFaqSchema={false}
          section="below-fold"
        />
      ) : null;

      return (
        <>
          <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
          <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(collectionPageSchema) }} />
          {itemListSchema && <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(itemListSchema) }} />}
          {faqPageSchema && <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqPageSchema) }} />}
          {merged.extraJsonLd.map((obj, i) => (
            <script
              // eslint-disable-next-line react/no-array-index-key -- supplementary schemas are stable per deploy
              key={`extra-ld-${canonicalSlug}-${i}`}
              type="application/ld+json"
              dangerouslySetInnerHTML={{ __html: JSON.stringify(obj) }}
            />
          ))}
          {productSchemas.map((schema, i) => (
            <script
              key={`product-schema-${canonicalSlug}-${i}`}
              type="application/ld+json"
              dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
            />
          ))}
          <Suspense
            fallback={
              <>
                <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12 lg:py-16">
                  <ProductsSkeleton />
                </main>
              </>
            }
          >
            <ShopPageClient
              productsData={productsData}
              categories={categories}
              brands={sub.brands ?? []}
              initialCategory={canonicalSlug}
              isSubcategory
              parentCategory={sub.sous_category?.categorie?.slug ?? undefined}
              categoryBreadcrumbLabel={merged.breadcrumbLabel}
              categorySeoLanding={categorySeoLanding}
              categorySeoLandingBottom={categorySeoLandingBottom}
            />
          </Suspense>
        </>
      );
    }

    if (type === 'category') {
      const cat = data as {
        category: any;
        sous_categories: any[];
        products: any[];
        brands: any[];
      };
      const productsData = {
        products: cat.products ?? [],
        brands: cat.brands ?? [],
        categories: [],
      };
      const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'https://protein.tn';
      const seoJsonCat = await getCategorySeoContent(canonicalSlug);
      const apiSeoCat = (cat as { seo?: CategorySeoFromApi }).seo;
      const mergedCat = mergeCategorySeo(seoJsonCat, apiSeoCat);
      const catCrumbName = mergedCat.breadcrumbLabel || mergedCat.h1?.trim() || cat.category?.designation_fr || canonicalSlug;
      const breadcrumbItems = [
        { name: 'Accueil', url: '/' },
        { name: catCrumbName, url: `/${canonicalSlug}` },
      ];
      const breadcrumbSchema = buildBreadcrumbListSchema(breadcrumbItems, baseUrl);
      validateStructuredData(breadcrumbSchema, 'BreadcrumbList');
      const pageTitleCat = mergedCat.h1?.trim() || cat.category?.designation_fr || canonicalSlug;
      const collectionDescCat =
        (mergedCat.metaDescription ||
          mergedCat.intro?.replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim() ||
          '')
          .slice(0, 500)
          .trim() || undefined;
      const collectionPageSchemaCat = buildCollectionPageSchema(pageTitleCat, `/${canonicalSlug}`, baseUrl, {
        description: collectionDescCat,
      });
      validateStructuredData(collectionPageSchemaCat, 'CollectionPage');
      const productListCat = (cat.products ?? []).slice(0, 20)
        // Use the canonical product URL so ItemList entries match each Product schema's offers.url.
        .map((p: any) => ({ name: p.designation_fr || p.slug, url: getProductLink(p) }))
        .filter((p: { name: string; url: string }) => p.url && p.url !== '/shop/');
      const itemListSchemaCat = productListCat.length > 0 ? buildItemListSchema(productListCat, baseUrl, { name: pageTitleCat }) : null;
      const productSchemasCat = (cat.products ?? [])
        .slice(0, 6)
        .map((p: any) => buildProductSchema(p, baseUrl))
        .filter(Boolean) as object[];

      const title = mergedCat.h1?.trim() || cat.category?.designation_fr || canonicalSlug;
      // Unique intro fallback (thin-content): when there is no admin/content-file intro, synthesize a
      // distinct paragraph from this category's real product data (count, brands, price) + its own
      // subcategory names so every indexed category carries non-duplicate copy.
      const introDataCat = deriveIntroDataFromProducts(cat.products ?? []);
      const subcategoryNamesCat = (cat.sous_categories ?? [])
        .map((s: any) => s?.designation_fr)
        .filter((n: unknown): n is string => typeof n === 'string' && n.trim().length > 0);
      const introForLandingCat = mergedCat.intro?.trim()
        ? mergedCat.intro
        : generateCategoryIntroFallback({
            name: title,
            productCount: introDataCat.productCount,
            topBrands: introDataCat.topBrands,
            priceMin: introDataCat.priceMin,
            subcategoryNames: subcategoryNamesCat,
          });
      const relatedSlugs = (mergedCat.relatedCategorySlugs?.length
        ? mergedCat.relatedCategorySlugs
        : categories.filter((c) => c.slug !== canonicalSlug).slice(0, 6).map((c) => c.slug)) as string[];
      const relatedCategories = resolveRelatedCategories(relatedSlugs, categories);
      const bestProducts = resolveBestProducts(
        mergedCat.bestProductSlugs?.length ? mergedCat.bestProductSlugs : (productsData.products as any[]).slice(0, 6).map((p: any) => p.slug).filter(Boolean),
        productsData.products as any[]
      );
      const faqPageSchemaCat = mergedCat.faqs?.length ? buildFAQPageSchemaFromQA(mergedCat.faqs) : null;
      if (faqPageSchemaCat) validateStructuredData(faqPageSchemaCat, 'FAQPage');
      const categorySeoLanding = (
        <CategorySeoLanding
          title={title}
          banners={mergedCat.banners}
          intro={introForLandingCat}
          longBottomHtml={null}
          howToChooseTitle={mergedCat.howToChooseTitle?.trim() ? mergedCat.howToChooseTitle : null}
          howToChooseBody={mergedCat.howToChooseBody?.trim() ? mergedCat.howToChooseBody : null}
          faqs={mergedCat.faqs ?? []}
          relatedCategories={relatedCategories}
          bestProducts={bestProducts}
          withFaqSchema={false}
          section="header"
        />
      );
      const hasHowToCat = Boolean(mergedCat.howToChooseTitle?.trim() && mergedCat.howToChooseBody?.trim());
      const hasLongBottomCat = Boolean((mergedCat.longBottomHtml ?? '').trim().length > 0);
      const hasSeoContentBelowCat =
        (introForLandingCat ?? '').trim().length > 0 ||
        (mergedCat.faqs?.length ?? 0) > 0 ||
        hasHowToCat ||
        hasLongBottomCat ||
        relatedCategories.length > 0 ||
        bestProducts.length > 0;
      const categorySeoLandingBottom = hasSeoContentBelowCat ? (
        <CategorySeoLanding
          title={title}
          intro={introForLandingCat}
          longBottomHtml={mergedCat.longBottomHtml?.trim() ? mergedCat.longBottomHtml : null}
          howToChooseTitle={mergedCat.howToChooseTitle?.trim() ? mergedCat.howToChooseTitle : null}
          howToChooseBody={mergedCat.howToChooseBody?.trim() ? mergedCat.howToChooseBody : null}
          faqs={mergedCat.faqs ?? []}
          relatedCategories={relatedCategories}
          bestProducts={bestProducts}
          withFaqSchema={false}
          section="below-fold"
        />
      ) : null;

      return (
        <>
          <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
          <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(collectionPageSchemaCat) }} />
          {itemListSchemaCat && <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(itemListSchemaCat) }} />}
          {faqPageSchemaCat && <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqPageSchemaCat) }} />}
          {mergedCat.extraJsonLd.map((obj, i) => (
            <script
              key={`extra-ld-cat-${canonicalSlug}-${i}`}
              type="application/ld+json"
              dangerouslySetInnerHTML={{ __html: JSON.stringify(obj) }}
            />
          ))}
          {productSchemasCat.map((schema, i) => (
            <script
              key={`product-schema-cat-${canonicalSlug}-${i}`}
              type="application/ld+json"
              dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
            />
          ))}
          <Suspense
            fallback={
              <>
                <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12 lg:py-16">
                  <ProductsSkeleton />
                </main>
              </>
            }
          >
            <ShopPageClient
              productsData={productsData}
              categories={categories}
              brands={cat.brands ?? []}
              initialCategory={canonicalSlug}
              categoryBreadcrumbLabel={mergedCat.breadcrumbLabel}
              categorySeoLanding={categorySeoLanding}
              categorySeoLandingBottom={categorySeoLandingBottom}
            />
          </Suspense>
        </>
      );
    }
  } catch (err) {
    // Preserve framework control-flow errors (notFound()/redirect() thrown inside the try).
    unstable_rethrow(err);
    console.error('Category/SubCategory fetch error:', err);
    // Only a GENUINE backend 404 is a 404. A transient failure (429/5xx/timeout) must rethrow —
    // on this ISR route a notFound() render would cache a wrong 404 for a healthy category for
    // the whole revalidate window. The rethrow hits the error boundary and is never cached.
    if (getErrorStatus(err) === 404) notFound();
    throw err;
  }

  notFound();
}


/**
 * Opt this route into the Full Route Cache. See the long note in app/(shop)/[slug]/page.tsx —
 * Next only registers a dynamic segment in prerenderManifest.dynamicRoutes when the route exports
 * generateStaticParams, and without that entry `export const revalidate` is inert and every
 * request re-renders. An EMPTY array is sufficient: on-demand ISR then covers every path.
 * Deliberately NOT enumerating the catalogue — `next build` runs in CI where Cloudflare 403s the
 * runner, so a fetched list would come back empty or partial and bake bad pages.
 */
export function generateStaticParams(): { slug: string }[] {
  return [];
}
